In [1]:
%load_ext sql
%config SqlMagic.style = '_DEPRECATED_DEFAULT'
from sqlalchemy import create_engine
import pandas as pd

In [2]:
%sql postgresql+psycopg://datalab:datalab@localhost:5432/nepal

In [3]:
%%sql
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema NOT IN ('pg_catalog', 'information_schema')

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
4 rows affected.

[('public', 'building_damage'),
 ('public', 'building_structure'),
 ('public', 'household_demographics'),
 ('public', 'id_map')]

In [6]:
%%sql
Select *
From id_map
limit 5;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
5 rows affected.

[(101, 1, 7, 1),
 (201, 2, 7, 1),
 (301, 3, 7, 1),
 (401, 4, 7, 1),
 (501, 5, 7, 1)]

In [5]:
%%sql
Select *
From building_structure
limit 5;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
5 rows affected.

[(1, 1, 1, 9, 288, 9, 9, 'Flat', 'Other', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar'),
 (2, 1, 1, 15, 364, 9, 9, 'Flat', 'Other', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar'),
 (3, 1, 1, 20, 384, 9, 9, 'Flat', 'Other', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar'),
 (4, 1, 1, 20, 312, 9, 9, 'Flat', 'Other', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar'),
 (5, 1, 1, 30, 308, 9, 9, 'Flat', 'Other', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar')]

In [9]:
%%sql
Select count(distinct(building_id))
From building_structure
limit 5;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(234835,)]

In [10]:
%%sql
Select count(*)
From id_map
limit 5;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(249932,)]

In [13]:
%%sql
Select count(distinct(district_id))
From id_map;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(4,)]

In [14]:
%%sql
Select distinct(district_id)
From id_map;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
4 rows affected.

[(1,), (2,), (3,), (4,)]

In [15]:
%%sql
Select count(*)
From id_map
where district_id = 1;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(36112,)]

In [16]:
%%sql
Select count(*)
From id_map
where district_id = 2;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(55253,)]

In [17]:
%%sql
Select count(*)
From id_map
where district_id = 3;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(82684,)]

In [18]:
%%sql
Select count(*)
From id_map
where district_id = 4;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(75883,)]

In [19]:
%%sql
Select *
From id_map
where district_id = 4
limit 5;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
5 rows affected.

[(16400001, 164000, 38, 4),
 (16400101, 164001, 38, 4),
 (16400201, 164002, 38, 4),
 (16400301, 164003, 38, 4),
 (16400401, 164004, 38, 4)]

In [22]:
%%sql
Select count(*)
From id_map i
Join building_structure bs
On i.building_id = bs.building_id
where district_id = 4
limit 5;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(75883,)]

In [21]:
%%sql
Select *
From id_map i
Join building_structure bs
On i.building_id = bs.building_id
where district_id = 4
limit 5;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
5 rows affected.

[(16400001, 164000, 38, 4, 164000, 1, 0, 40, 336, 6, 0, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Rubble unclear', 'Stone, mud mortar'),
 (16400101, 164001, 38, 4, 164001, 2, 2, 12, 420, 13, 13, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar'),
 (16400201, 164002, 38, 4, 164002, 3, 3, 20, 560, 18, 18, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar'),
 (16400301, 164003, 38, 4, 164003, 2, 2, 15, 390, 12, 12, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar'),
 (16400401, 164004, 38, 4, 164004, 2, 2, 15, 290, 13, 13, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Square', 'Damaged-Not used', 'Stone, mud mortar')]

In [23]:
%%sql
Select distinct(i.building_id),
        bs.*
From id_map i
Join building_structure bs
On i.building_id = bs.building_id
where district_id = 4
limit 5;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
5 rows affected.

[(164000, 164000, 1, 0, 40, 336, 6, 0, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Rubble unclear', 'Stone, mud mortar'),
 (164001, 164001, 2, 2, 12, 420, 13, 13, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar'),
 (164002, 164002, 3, 3, 20, 560, 18, 18, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar'),
 (164003, 164003, 2, 2, 15, 390, 12, 12, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar'),
 (164004, 164004, 2, 2, 15, 290, 13, 13, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Square', 'Damaged-Not used', 'Stone, mud mortar')]

In [24]:
%%sql
Select *
From building_damage
limit 5;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
5 rows affected.

[(1, 'Moderate-Heavy', 'Insignificant/light', None, None, 'Moderate-Heavy-(<1/3)', 'Insignificant/light-(<1/3)', 'Severe-Extreme-(<1/3)', None, 'Insignificant/light-(>2/3)', 'Severe-Extreme-(>2/3)', None, None, 'Severe-Extreme-(<1/3)', None, None, 'Severe-Extreme-(>2/3)', None, None, None, 'Moderate-Heavy-(>2/3)', None, 'Severe-Extreme-(>2/3)', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'Both', 'Grade 3', 'Major repair', 0.0, None, 1.0, 1.0, 1.0, 1.0, None, 1.0, 0.0, 0.0, None, None, None, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0),
 (2, 'Severe-Extreme', 'Severe-Extreme', 'Insignificant/light', 'Severe-Extreme-(>2/3)', None, None, 'Severe-Extreme-(>2/3)', None, None, 'Severe-Extreme-(>2/3)', None, None, 'Severe-Extreme-(>2/3)', None, None, 'Severe-Extreme-(>2/3)', None, None, 'Severe-Extreme-(>2/3)', None, None, 'Severe-Extreme-(>2/3)', None, None, None, None, None, 'Severe-Extreme-(>2/3)', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'Exterior', 'Grade 5', 'Reconstruction', 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, None, None, None, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0),
 (3, 'Moderate-Heavy', 'Moderate-Heavy', 'Moderate-Heavy', None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, None, 'Insignificant/light-(1/3-2/3)', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'Both', 'Grade 2', 'Minor repair', 1.0, None, None, None, None, None, None, None, None, None, None, None, None, 1.0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0),
 (4, 'Moderate-Heavy', 'Moderate-Heavy', 'Moderate-Heavy', None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, 'Moderate-Heavy-(>2/3)', None, None, None, 'Insignificant/light-(<1/3)', None, None, 'Insignificant/light-(1/3-2/3)', None, None, None, None, None, None, None, None, None, None, 'Moderate-Heavy-(>2/3)', None, None, None, None, None, None, None, 'Both', 'Grade 2', 'Minor repair', 1.0, None, None, None, None, None, None, None, None, None, None, None, None, None, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0),
 (5, 'Insignificant/light', None, None, None, None, 'Insignificant/light-(<1/3)', None, None, 'Insignificant/light-(<1/3)', None, None, 'Insignificant/light-(<1/3)', None, None, 'Insignificant/light-(<1/3)', None, None, 'Insignificant/light-(<1/3)', None, None, 'Insignificant/light-(<1/3)', None, None, 'Insignificant/light-(<1/3)', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'Exterior', 'Grade 1', 'Minor repair', 1.0, None, None, None, None, None, None, None, 0.0, 0.0, None, None, None, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0)]

In [26]:
%%sql
Select distinct(i.building_id),
        bs.*,
        bd.damage_grade
From id_map i
Join building_structure bs
On i.building_id = bs.building_id
Join building_damage bd
On bs.building_id = bd.building_id
where i.district_id = 4
limit 5;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
5 rows affected.

[(164000, 164000, 1, 0, 40, 336, 6, 0, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Rubble unclear', 'Stone, mud mortar', 'Grade 5'),
 (164001, 164001, 2, 2, 12, 420, 13, 13, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar', 'Grade 3'),
 (164002, 164002, 3, 3, 20, 560, 18, 18, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar', 'Grade 2'),
 (164003, 164003, 2, 2, 15, 390, 12, 12, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar', 'Grade 4'),
 (164004, 164004, 2, 2, 15, 290, 13, 13, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Square', 'Damaged-Not used', 'Stone, mud mortar', 'Grade 4')]

In [27]:
engine = create_engine("postgresql+psycopg://datalab:datalab@localhost:5432/nepal")

In [28]:
query = """
        SELECT DISTINCT(i.building_id),
                bs.*,
                bd.damage_grade
        FROM id_map i
        JOIN building_structure bs
        ON i.building_id = bs.building_id
        JOIN building_damage bd
        ON bs.building_id = bd.building_id
        WHERE i.district_id = 4
"""
print(query)

        SELECT DISTINCT(i.building_id),
                bs.*,
                bd.damage_grade
        FROM id_map i
        JOIN building_structure bs
        ON i.building_id = bs.building_id
        JOIN building_damage bd
        ON bs.building_id = bd.building_id
        WHERE i.district_id = 4

In [29]:
df = pd.read_sql(query, engine)
df.head()

,building_id,building_id,count_floors_pre_eq,count_floors_post_eq,age_building,plinth_area_sq_ft,height_ft_pre_eq,height_ft_post_eq,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,condition_post_eq,superstructure,damage_grade
0,164000,164000,1,0,40,336,6,0,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,Not applicable,Not attached,Rectangular,Damaged-Rubble unclear,"Stone, mud mortar",Grade 5
1,164001,164001,2,2,12,420,13,13,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Damaged-Used in risk,"Stone, mud mortar",Grade 3
2,164002,164002,3,3,20,560,18,18,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Damaged-Repaired and used,"Stone, mud mortar",Grade 2
3,164003,164003,2,2,15,390,12,12,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Damaged-Used in risk,"Stone, mud mortar",Grade 4
4,164004,164004,2,2,15,290,13,13,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Square,Damaged-Not used,"Stone, mud mortar",Grade 4

In [30]:
df.columns

Index(['building_id', 'building_id', 'count_floors_pre_eq',
       'count_floors_post_eq', 'age_building', 'plinth_area_sq_ft',
       'height_ft_pre_eq', 'height_ft_post_eq', 'land_surface_condition',
       'foundation_type', 'roof_type', 'ground_floor_type', 'other_floor_type',
       'position', 'plan_configuration', 'condition_post_eq', 'superstructure',
       'damage_grade'],
      dtype='str')

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70836 entries, 0 to 70835
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   building_id             70836 non-null  int64
 1   building_id             70836 non-null  int64
 2   count_floors_pre_eq     70836 non-null  int64
 3   count_floors_post_eq    70836 non-null  int64
 4   age_building            70836 non-null  int64
 5   plinth_area_sq_ft       70836 non-null  int64
 6   height_ft_pre_eq        70836 non-null  int64
 7   height_ft_post_eq       70836 non-null  int64
 8   land_surface_condition  70836 non-null  str
 9   foundation_type         70836 non-null  str
 10  roof_type               70836 non-null  str
 11  ground_floor_type       70836 non-null  str
 12  other_floor_type        70836 non-null  str
 13  position                70836 non-null  str
 14  plan_configuration      70836 non-null  str
 15  condition_post_eq       70836 non-null  str
 16  superstructure          70836 non-null  str
 17  damage_grade            70836 non-null  str
dtypes: int64(8), str(10)
memory usage: 9.7 MB

In [32]:
df.damage_grade.value_counts()

damage_grade
Grade 5    24869
Grade 4    20650
Grade 3    14097
Grade 2     7650
Grade 1     3570
Name: count, dtype: int64

In [38]:
df["damage_grade"] = df.damage_grade.str[-1].astype(int)

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70836 entries, 0 to 70835
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   building_id             70836 non-null  int64
 1   building_id             70836 non-null  int64
 2   count_floors_pre_eq     70836 non-null  int64
 3   count_floors_post_eq    70836 non-null  int64
 4   age_building            70836 non-null  int64
 5   plinth_area_sq_ft       70836 non-null  int64
 6   height_ft_pre_eq        70836 non-null  int64
 7   height_ft_post_eq       70836 non-null  int64
 8   land_surface_condition  70836 non-null  str
 9   foundation_type         70836 non-null  str
 10  roof_type               70836 non-null  str
 11  ground_floor_type       70836 non-null  str
 12  other_floor_type        70836 non-null  str
 13  position                70836 non-null  str
 14  plan_configuration      70836 non-null  str
 15  condition_post_eq       70836 non-null  str
 16  superstructure          70836 non-null  str
 17  damage_grade            70836 non-null  int64
dtypes: int64(9), str(9)
memory usage: 9.7 MB

In [42]:
df["severe_damage"] = (df.damage_grade > 3).astype(int)

In [43]:
df.head()

,building_id,building_id,count_floors_pre_eq,count_floors_post_eq,age_building,plinth_area_sq_ft,height_ft_pre_eq,height_ft_post_eq,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,condition_post_eq,superstructure,damage_grade,severe_damage
0,164000,164000,1,0,40,336,6,0,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,Not applicable,Not attached,Rectangular,Damaged-Rubble unclear,"Stone, mud mortar",5,1
1,164001,164001,2,2,12,420,13,13,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Damaged-Used in risk,"Stone, mud mortar",3,0
2,164002,164002,3,3,20,560,18,18,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Damaged-Repaired and used,"Stone, mud mortar",2,0
3,164003,164003,2,2,15,390,12,12,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Damaged-Used in risk,"Stone, mud mortar",4,1
4,164004,164004,2,2,15,290,13,13,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Square,Damaged-Not used,"Stone, mud mortar",4,1

In [45]:
#df.drop(columns=[col1, col2, col3]

for cols in df.columns:
    if "post_eq" in cols:
        print(cols)

count_floors_post_eq
height_ft_post_eq
condition_post_eq

In [48]:
result = [cols for cols in df.columns if "post_eq" in cols]

df.drop(columns=result, inplace=True)

In [49]:
df.columns

Index(['building_id', 'building_id', 'count_floors_pre_eq', 'age_building',
       'plinth_area_sq_ft', 'height_ft_pre_eq', 'land_surface_condition',
       'foundation_type', 'roof_type', 'ground_floor_type', 'other_floor_type',
       'position', 'plan_configuration', 'superstructure', 'damage_grade',
       'severe_damage'],
      dtype='str')