<font size="+3"><strong>Working with JSON files</strong></font>

In [1]:
import gzip
import json
import pickle 

import pandas as pd

# Prepare Data

In [2]:
df = pd.read_json("data/poland-bankruptcy-data-2009.json")
df.head()

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [3]:
with open("data/poland-bankruptcy-data-2009.json", "r") as file:
    data = json.load(file)

data

{'schema': {'fields': [{'name': 'company_id', 'type': 'integer'},
   {'name': 'feat_1', 'type': 'number'},
   {'name': 'feat_2', 'type': 'number'},
   {'name': 'feat_3', 'type': 'number'},
   {'name': 'feat_4', 'type': 'number'},
   {'name': 'feat_5', 'type': 'number'},
   {'name': 'feat_6', 'type': 'number'},
   {'name': 'feat_7', 'type': 'number'},
   {'name': 'feat_8', 'type': 'number'},
   {'name': 'feat_9', 'type': 'number'},
   {'name': 'feat_10', 'type': 'number'},
   {'name': 'feat_11', 'type': 'number'},
   {'name': 'feat_12', 'type': 'number'},
   {'name': 'feat_13', 'type': 'number'},
   {'name': 'feat_14', 'type': 'number'},
   {'name': 'feat_15', 'type': 'number'},
   {'name': 'feat_16', 'type': 'number'},
   {'name': 'feat_17', 'type': 'number'},
   {'name': 'feat_18', 'type': 'number'},
   {'name': 'feat_19', 'type': 'number'},
   {'name': 'feat_20', 'type': 'number'},
   {'name': 'feat_21', 'type': 'number'},
   {'name': 'feat_22', 'type': 'number'},
   {'name': 'feat_23', 'type': 'number'},
   {'name': 'feat_24', 'type': 'number'},
   {'name': 'feat_25', 'type': 'number'},
   {'name': 'feat_26', 'type': 'number'},
   {'name': 'feat_27', 'type': 'number'},
   {'name': 'feat_28', 'type': 'number'},
   {'name': 'feat_29', 'type': 'number'},
   {'name': 'feat_30', 'type': 'number'},
   {'name': 'feat_31', 'type': 'number'},
   {'name': 'feat_32', 'type': 'number'},
   {'name': 'feat_33', 'type': 'number'},
   {'name': 'feat_34', 'type': 'number'},
   {'name': 'feat_35', 'type': 'number'},
   {'name': 'feat_36', 'type': 'number'},
   {'name': 'feat_37', 'type': 'number'},
   {'name': 'feat_38', 'type': 'number'},
   {'name': 'feat_39', 'type': 'number'},
   {'name': 'feat_40', 'type': 'number'},
   {'name': 'feat_41', 'type': 'number'},
   {'name': 'feat_42', 'type': 'number'},
   {'name': 'feat_43', 'type': 'number'},
   {'name': 'feat_44', 'type': 'number'},
   {'name': 'feat_45', 'type': 'number'},
   {'name': 'feat_46', 'type': 'number'},
   {'name': 'feat_47', 'type': 'number'},
   {'name': 'feat_48', 'type': 'number'},
   {'name': 'feat_49', 'type': 'number'},
   {'name': 'feat_50', 'type': 'number'},
   {'name': 'feat_51', 'type': 'number'},
   {'name': 'feat_52', 'type': 'number'},
   {'name': 'feat_53', 'type': 'number'},
   {'name': 'feat_54', 'type': 'number'},
   {'name': 'feat_55', 'type': 'number'},
   {'name': 'feat_56', 'type': 'number'},
   {'name': 'feat_57', 'type': 'number'},
   {'name': 'feat_58', 'type': 'number'},
   {'name': 'feat_59', 'type': 'number'},
   {'name': 'feat_60', 'type': 'number'},
   {'name': 'feat_61', 'type': 'number'},
   {'name': 'feat_62', 'type': 'number'},
   {'name': 'feat_63', 'type': 'number'},
   {'name': 'feat_64', 'type': 'number'},
   {'name': 'bankrupt', 'type': 'boolean'}],
  'primaryKey': ['company_id'],
  'pandas_version': '0.20.0'},
 'data': [{'company_id': 1,
   'feat_1': 0.17419,
   'feat_2': 0.41299,
   'feat_3': 0.14371,
   'feat_4': 1.348,
   'feat_5': -28.982,
   'feat_6': 0.60383,
   'feat_7': 0.21946,
   'feat_8': 1.1225,
   'feat_9': 1.1961,
   'feat_10': 0.46359,
   'feat_11': 0.21946,
   'feat_12': 0.53139,
   'feat_13': 0.14233,
   'feat_14': 0.21946,
   'feat_15': 592.24,
   'feat_16': 0.6163,
   'feat_17': 2.4213,
   'feat_18': 0.21946,
   'feat_19': 0.12272,
   'feat_20': 37.573,
   'feat_21': 0.9969,
   'feat_22': 0.2951,
   'feat_23': 0.097402,
   'feat_24': 0.75641,
   'feat_25': 0.46359,
   'feat_26': 0.50669,
   'feat_27': 1.9737,
   'feat_28': 0.32417,
   'feat_29': 5.9473,
   'feat_30': 0.22493,
   'feat_31': 0.12272,
   'feat_32': 100.82,
   'feat_33': 3.6203,
   'feat_34': 0.71453,
   'feat_35': 0.2951,
   'feat_36': 1.8079,
   'feat_37': 123140.0,
   'feat_38': 0.46359,
   'feat_39': 0.16501,
   'feat_40': 0.21282,
   'feat_41': 0.041124,
   'feat_42': 0.16501,
   'feat_43': 95.682,
   'feat_44': 58.109,
   'feat_45': 0.94621,
   'feat_46': 0.90221,
   'feat_47': 44.941,
   'feat_48': 0.26003,
   'feat_49': 0.1454,
   'feat_50': 1.348,
   'feat_51': 0.41299,
   'feat_52': 0.27622,
   'feat_53': 1.0457,
   'feat_54': 1.0458,
   'feat_55': 127280.0,
   'feat_56': 0.16396,
   'feat_57': 0.37574,
   'feat_58': 0.83604,
   'feat_59': 6.5269e-06,
   'feat_60': 9.7145,
   'feat_61': 6.2813,
   'feat_62': 84.291,
   'feat_63': 4.3303,
   'feat_64': 4.0341,
   'bankrupt': False},
  {'company_id': 2,
   'feat_1': 0.14624,
   'feat_2': 0.46038,
   'feat_3': 0.2823,
   'feat_4': 1.6294,
   'feat_5': 2.5952,
   'feat_6': 0.0,
   'feat_7': 0.17185,
   'feat_8': 1.1721,
   'feat_9': 1.6018,
   'feat_10': 0.53962,
   'feat_11': 0.17579,
   'feat_12': 0.38317,
   'feat_13': 0.12647,
   'feat_14': 0.17185,
   'feat_15': 829.46,
   'feat_16': 0.44004,
   'feat_17': 2.1721,
   'feat_18': 0.17185,
   'feat_19': 0.10728,
   'feat_20': 60.954,
   'feat_21': 5.0889,
   'feat_22': 0.17571,
   'feat_23': 0.091295,
   'feat_24': None,
   'feat_25': 0.17523,
   'feat_26': 0.38442,
   'feat_27': 44.593,
   'feat_28': 1.0486,
   'feat_29': 4.0792,
   'feat_30': 0.24384,
   'feat_31': 0.10974,
   'feat_32': 105.09,
   'feat_33': 3.4733,
   'feat_34': 3.3836,
   'feat_35': 0.044076,
   'feat_36': 1.6018,
   'feat_37': None,
   'feat_38': 0.53962,
   'feat_39': 0.027516,
   'feat_40': 0.16406,
   'feat_41': 0.074333,
   'feat_42': 0.10969,
   'feat_43': 149.75,
   'feat_44': 88.801,
   'feat_45': 0.54669,
   'feat_46': 1.033,
   'feat_47': 62.678,
   'feat_48': 0.14497,
   'feat_49': 0.090503,
   'feat_50': 1.5874,
   'feat_51': 0.44849,
   'feat_52': 0.28791,
   'feat_53': 2.0044,
   'feat_54': 2.0044,
   'feat_55': 3387.8,
   'feat_56': 0.027516,
   'feat_57': 0.271,
   'feat_58': 0.90108,
   'feat_59': 0.0,
   'feat_60': 5.9882,
   'feat_61': 4.1103,
   'feat_62': 102.19,
   'feat_63': 3.5716,
   'feat_64': 5.95,
   'bankrupt': False},
  {'company_id': 3,
   'feat_1': 0.00059529,
   'feat_2': 0.22612,
   'feat_3': 0.48839,
   'feat_4': 3.1599,
   'feat_5': 84.874,
   'feat_6': 0.19114,
   'feat_7': 0.0045718,
   'feat_8': 2.9881,
   'feat_9': 1.0077,
   'feat_10': 0.67566,
   'feat_11': 0.0045718,
   'feat_12': 0.020219,
   'feat_13': 0.030966,
   'feat_14': 0.0045718,
   'feat_15': 2094.1,
   'feat_16': 0.1743,
   'feat_17': 4.4225,
   'feat_18': 0.0045718,
   'feat_19': 0.0035921,
   'feat_20': 53.881,
   'feat_21': 0.67451,
   'feat_22': 0.04061,
   'feat_23': 0.00046772,
   'feat_24': 0.2347,
   'feat_25': 0.67566,
   'feat_26': 0.15672,
   'feat_27': 0.32153,
   'feat_28': 1.7107,
   'feat_29': 4.622,
   'feat_30': 0.036196,
   'feat_31': 0.0035921,
   'feat_32': 65.345,
   'feat_33': 5.5857,
   'feat_34': 0.1796,
   'feat_35': 0.04061,
   'feat_36': 1.3425,
   'feat_37': None,
   'feat_38': 0.67566,
   'feat_39': 0.031907,
   'feat_40': 0.84469,
   'feat_41': 0.098528,
   'feat_42': 0.031907,
   'feat_43': 150.13,
   'feat_44': 96.251,
   'feat_45': 0.0031684,
   'feat_46': 2.329,
   'feat_47': 54.296,
   'feat_48': 0.0057691,
   'feat_49': 0.0045328,
   'feat_50': 3.1599,
   'feat_51': 0.22612,
   'feat_52': 0.17903,
   'feat_53': 2.3667,
   'feat_54': 2.3667,
   'feat_55': 20453.0,
   'feat_56': 0.0076387,
   'feat_57': 0.00088105,
   'feat_58': 0.99236,
   'feat_59': 0.0,
   'feat_60': 6.7742,
   'feat_61': 3.7922,
   'feat_62': 64.846,
   'feat_63': 5.6287,
   'feat_64': 4.4581,
   'bankrupt': False},
  {'company_id': 5,
   'feat_1': 0.18829,
   'feat_2': 0.41504,
   'feat_3': 0.34231,
   'feat_4': 1.9279,
   'feat_5': -58.274,
   'feat_6': 0.0,
   'feat_7': 0.23358,
   'feat_8': 1.4094,
   'feat_9': 1.3393,
   'feat_10': 0.58496,
   'feat_11': 0.23881,
   'feat_12': 0.63317,
   'feat_13': 0.1878,
   'feat_14': 0.23358,
   'feat_15': 602.31,
   'feat_16': 0.606,
   'feat_17': 2.4094,
   'feat_18': 0.23358,
   'feat_19': 0.17441,
   'feat_20': 140.86,
   'feat_21': 1.2039,
   'feat_22': 0.23493,
   'feat_23': 0.14059,
   'feat_24': 0.0,
   'feat_25': 0.5725,
   'feat_26': 0.49687,
   'feat_27': 44.947,
   'feat_28': 1.1853,
   'feat_29': 4.6033,
   'feat_30': 0.30691,
   'feat_31': 0.17784,
   'feat_32': 122.09,
   'feat_33': 2.9897,
   'feat_34': 2.6574,
   'feat_35': 0.23635,
   'feat_36': 1.3393,
   'feat_37': 4.549,
   'feat_38': 0.62769,
   'feat_39': 0.17648,
   'feat_40': 0.013769,
   'feat_41': 0.054712,
   'feat_42': 0.17542,
   'feat_43': 192.45,
   'feat_44': 51.585,
   'feat_45': 0.36429,
   'feat_46': 0.52685,
   'feat_47': 171.05,
   'feat_48': 0.21699,
   'feat_49': 0.16203,
   'feat_50': 1.7136,
   'feat_51': 0.36891,
   'feat_52': 0.33449,
   'feat_53': 2.0256,
   'feat_54': 2.1735,
   'feat_55': 13730.0,
   'feat_56': 0.17648,
   'feat_57': 0.32188,
   'feat_58': 0.82635,
   'feat_59': 0.073039,
   'feat_60': 2.5912,
   'feat_61': 7.0756,
   'feat_62': 100.54,
   'feat_63': 3.6303,
   'feat_64': 4.6375,
   'bankrupt': False},
  {'company_id': 6,
   'feat_1': 0.18206,
   'feat_2': 0.55615,
   'feat_3': 0.32191,
   'feat_4': 1.6045,
   'feat_5': 16.314,
   'feat_6': 0.0,
   'feat_7': 0.18206,
   'feat_8': 0.79808,
   'feat_9': 1.8126,
   'feat_10': 0.44385,
   'feat_11': 0.20766,
   'feat_12': 0.34188,
   'feat_13': 0.27163,
   'feat_14': 0.18206,
   'feat_15': 412.3,
   'feat_16': 0.88528,
   'feat_17': 1.7981,
   'feat_18': 0.18206,
   'feat_19': 0.10045,
   'feat_20': 43.168,
   'feat_21': 1.2724,
   'feat_22': 0.0,
   'feat_23': 0.10045,
   'feat_24': None,
   'feat_25': 0.416,
   'feat_26': 0.88528,
   'feat_27': 0.0,
   'feat_28': 2.2118,
   'feat_29': 3.8104,
   'feat_30': 0.29926,
   'feat_31': 0.22877,
   'feat_32': 241.41,
   'feat_33': 1.512,
   'feat_34': 1.4478,
   'feat_35': 0.029538,
   'feat_36': 1.8126,
   'feat_37': 49.017,
   'feat_38': 0.45691,
   'feat_39': 0.016296,
   'feat_40': 0.1856,
   'feat_41': 0.059746,
   'feat_42': 0.0,
   'feat_43': 152.16,
   'feat_44': 108.99,
   'feat_45': 0.8493,
   'feat_46': 1.2019,
   'feat_47': 97.177,
   'feat_48': -0.31028,
   'feat_49': -0.17119,
   'feat_50': 1.5364,
   'feat_51': 0.53254,
   'feat_52': 0.6614,
   'feat_53': 3.0496,
   'feat_54': 3.1393,
   'feat_55': 2080.6,
   'feat_56': 0.55577,
   'feat_57': 0.41019,
   'feat_58': 0.46957,
   'feat_59': 0.029421,
   'feat_60': 8.4553,
   'feat_61': 3.3488,
   'feat_62': 107.24,
   'feat_63': 3.4036,
   'feat_64': 12.454,
   'bankrupt': False},
  {'company_id': 7,
   'feat_1': 0.11503,
   'feat_2': 0.036659,
   'feat_3': 0.92345,
   'feat_4': 112.63,
   'feat_5': 55.58,
   'feat_6': 0.0,
   'feat_7': 0.14215,
   'feat_8': 26.279,
   'feat_9': 0.44339,
   'feat_10': 0.96334,
   'feat_11': 0.1435,
   'feat_12': 17.183,
   'feat_13': 0.32533,
   'feat_14': 0.14215,
   'feat_15': 92.759,
   'feat_16': 3.9349,
   'feat_17': 27.279,
   'feat_18': 0.14215,
   'feat_19': 0.32061,
   'feat_20': 19.801,
   'feat_21': 0.82872,
   'feat_22': 0.082265,
   'feat_23': 0.25943,
   'feat_24': 10.573,
   'feat_25': 0.96082,
   'feat_26': 3.195,
   'feat_27': 61.21,
   'feat_28': 13.526,
   'feat_29': 4.339,
   'feat_30': -0.055356,
   'feat_31': 0.32222,
   'feat_32': 7.2995,
   'feat_33': 50.003,
   'feat_34': 11.284,
   'feat_35': 0.029724,
   'feat_36': 0.44339,
   'feat_37': 58.907,
   'feat_38': 0.97875,
   'feat_39': 0.067038,
   'feat_40': 108.44,
   'feat_41': 0.014485,
   'feat_42': 0.18554,
   'feat_43': 28.536,
   'feat_44': 8.7355,
   'feat_45': 4.7821,
   'feat_46': 109.72,
   'feat_47': 21.224,
   'feat_48': 0.080169,
   'feat_49': 0.18081,
   'feat_50': 25.416,
   'feat_51': 0.0082728,
   'feat_52': 0.019999,
   'feat_53': 14.11,
   'feat_54': 14.336,
   'feat_55': 20158.0,
   'feat_56': 0.067038,
   'feat_57': 0.1194,
   'feat_58': 0.75777,
   'feat_59': 0.015995,
   'feat_60': 18.433,
   'feat_61': 41.783,
   'feat_62': 6.8102,
   'feat_63': 53.596,
   'feat_64': 6.4942,
   'bankrupt': False},
  {'company_id': 8,
   'feat_1': 0.0098323,
   'feat_2': 0.67066,
   'feat_3': 0.13546,
   'feat_4': 1.2393,
   'feat_5': -107.73,
   'feat_6': -0.0014006,
   'feat_7': 0.013422,
   'feat_8': 0.49108,
   'feat_9': 1.1825,
   'feat_10': 0.32934,
   'feat_11': 0.055717,
   'feat_12': 0.023711,
   'feat_13': 0.047491,
   'feat_14': 0.013422,
   'feat_15': 4359.1,
   'feat_16': 0.083733,
   'feat_17': 1.4911,
   'feat_18': 0.013422,
   'feat_19': 0.011351,
   'feat_20': 44.614,
   'feat_21': 1.013,
   'feat_22': 0.04612,
   'feat_23': 0.0083151,
   'feat_24': 0.0,
   'feat_25': 0.3105,
   'feat_26': 0.078381,
   'feat_27': 1.0904,
   'feat_28': 0.45384,
   'feat_29': 5.9673,
   'feat_30': 0.56717,
   'feat_31': 0.011351,
   'feat_32': 217.81,
   'feat_33': 1.7455,
   'feat_34': 1.4733,
   'feat_35': 0.23389,
   'feat_36': 1.1825,
   'feat_37': 11.749,
   'feat_38': 0.37675,
   'feat_39': 0.1978,
   'feat_40': 0.46285,
   'feat_41': 0.25159,
   'feat_42': 0.039003,
   'feat_43': 135.67,
   'feat_44': 91.058,
   'feat_45': 0.068029,
   'feat_46': 0.98398,
   'feat_47': 53.392,
   'feat_48': 0.0033856,
   'feat_49': 0.0028632,
   'feat_50': 1.046,
   'feat_51': 0.56606,
   'feat_52': 0.57291,
   'feat_53': 1.1034,
   'feat_54': 1.2622,
   'feat_55': 1.2393,
   'feat_56': 0.1978,
   'feat_57': 0.029854,
   'feat_58': 0.83478,
   'feat_59': 0.14394,
   'feat_60': 8.1813,
   'feat_61': 4.0084,
   'feat_62': 174.73,
   'feat_63': 2.0889,
   'feat_64': 3.9616,
   'bankrupt': False},
  {'company_id': 9,
   'feat_1': 0.23895,
   'feat_2': 0.55473,
   'feat_3': 0.40697,
   'feat_4': 1.7609,
   'feat_5': -22.907,
   'feat_6': 0.0,
   'feat_7': 0.29714,
   'feat_8': 0.80268,
   'feat_9': 2.3317,
   'feat_10': 0.44527,
   'feat_11': 0.33061,
   'feat_12': 0.55553,
   'feat_13': 0.13198,
   'feat_14': 0.29714,
   'feat_15': 657.95,
   'feat_16': 0.55475,
   'feat_17': 1.8027,
   'feat_18': 0.29714,
   'feat_19': 0.12743,
   'feat_20': 81.972,
   'feat_21': 1.0467,
   'feat_22': 0.33015,
   'feat_23': 0.10248,
   'feat_24': None,
   'feat_25': 0.43913,
   'feat_26': 0.44985,
   'feat_27': 9.8633,
   'feat_28': 6.9983,
   'feat_29': 3.911,
   'feat_30': 0.20211,
   'feat_31': 0.13836,
   'feat_32': 97.4,
   'feat_33': 3.7474,
   'feat_34': 3.6133,
   'feat_35': 0.32732,
   'feat_36': 2.3317,
   'feat_37': 21.065,
   'feat_38': 0.46512,
   'feat_39': 0.14038,
   'feat_40': 0.17507,
   'feat_41': 0.054265,
   'feat_42': 0.14159,
   'feat_43': 132.77,
   'feat_44': 50.802,
   'feat_45': 0.4563,
   'feat_46': 0.78182,
   'feat_47': 95.359,
   'feat_48': 0.31955,
   'feat_49': 0.13704,
   'feat_50': 1.6978,
   'feat_51': 0.53488,
   'feat_52': 0.26685,
   'feat_53': 7.6569,
   'feat_54': 7.9983,
   'feat_55': 3315.2,
   'feat_56': 0.14038,
   'feat_57': 0.53663,
   'feat_58': 0.87292,
   'feat_59': 0.044584,
   'feat_60': 4.4527,
   'feat_61': 7.1847,
   'feat_62': 83.727,
   'feat_63': 4.3594,
   'feat_64': 40.097,
   'bankrupt': False},
  {'company_id': 10,
   'feat_1': -0.11986,
   'feat_2': 0.60733,
   'feat_3': 0.041368,
   'feat_4': 1.0688,
   'feat_5': -37.595,
   'feat_6': -0.44797,
   'feat_7': -0.11986,
   'feat_8': 0.64655,
   'feat_9': 3.0,
   'feat_10': 0.39267,
   'feat_11': -0.11986,
   'feat_12': -0.1993,
   'feat_13': 0.011424,
   'feat_14': -0.11986,
   'feat_15': 6467.9,
   'feat_16': 0.056432,
   'feat_17': 1.6466,
   'feat_18': -0.11986,
   'feat_19': -0.039953,
   'feat_20': 28.419,
   'feat_21': 0.858,
   'feat_22': 0.0,
   'feat_23': -0.039953,
   'feat_24': None,
   'feat_25': -0.52078,
   'feat_26': 0.056432,
   'feat_27': None,
   'feat_28': 0.11581,
   'feat_29': 3.3322,
   'feat_30': 0.19386,
   'feat_31': -0.079906,
   'feat_32': 99.456,
   'feat_33': 3.67,
   'feat_34': 3.6342,
   'feat_35': 0.0069493,
   'feat_36': 3.0,
   'feat_37': None,
   'feat_38': 0.39267,
   'feat_39': 0.0023164,
   'feat_40': 0.079719,
   'feat_41': 0.13134,
   'feat_42': 0.0,
   'feat_43': 72.372,
   'feat_44': 43.953,
   'feat_45': -0.51315,
   'feat_46': 0.6804,
   'feat_47': 38.627,
   'feat_48': -0.15413,
   'feat_49': -0.051377,
   'feat_50': 1.0584,
   'feat_51': 0.60142,
   'feat_52': 0.27248,
   'feat_53': 1.0993,
   'feat_54': 1.0993,
   'feat_55': 88.899,
   'feat_56': 0.26428,
   'feat_57': -0.30525,
   'feat_58': 0.73749,
   'feat_59': 0.0,
   'feat_60': 12.844,
   'feat_61': 8.3043,
   'feat_62': 73.172,
   'feat_63': 4.9883,
   'feat_64': 8.3984,
   'bankrupt': False},
  {'company_id': 11,
   'feat_1': -0.13035,
   'feat_2': 0.08968,
   'feat_3': 0.14907,
   'feat_4': 2.6622,
   'feat_5': -34.003,
   'feat_6': -0.20856,
   'feat_7': -0.12478,
   'feat_8': 8.9791,
   'feat_9': 0.76134,
   'feat_10': 0.80524,
   'feat_11': -0.12478,
   'feat_12': -1.3914,
   'feat_13': -0.025158,
   'feat_14': -0.12478,
   'feat_15': -2864.9,
   'feat_16': -0.12741,
   'feat_17': 11.151,
   'feat_18': -0.12478,
   'feat_19': -0.27475,
   'feat_20': 148.05,
   'feat_21': 0.68266,
   'feat_22': -0.12461,
   'feat_23': -0.28701,
   'feat_24': -0.19542,
   'feat_25': 0.80524,
   'feat_26': -0.18946,
   'feat_27': -2.0889,
   'feat_28': 0.19582,
   'feat_29': 4.0259,
   'feat_30': 0.18671,
   'feat_31': -0.27475,
   'feat_32': 54.873,
   'feat_33': 6.6517,
   'feat_34': -1.3895,
   'feat_35': -0.12461,
   'feat_36': 0.50197,
   'feat_37': None,
   'feat_38': 0.80524,
   'feat_39': -0.27437,
   'feat_40': 0.17146,
   'feat_41': -0.26207,
   'feat_42': -0.27437,
   'feat_43': 179.52,
   'feat_44': 31.473,
   'feat_45': -0.70761,
   'feat_46': 0.60813,
   'feat_47': 112.71,
   'feat_48': -0.23796,
   'feat_49': -0.52396,
   'feat_50': 2.6622,
   'feat_51': 0.08968,
   'feat_52': 0.15034,
   'feat_53': 1.0578,
   'feat_54': 1.0578,
   'feat_55': 1582.1,
   'feat_56': -0.31347,
   'feat_57': -0.16187,
   'feat_58': 1.3135,
   'feat_59': 0.0,
   'feat_60': 2.4655,
   'feat_61': 11.597,
   'feat_62': 72.074,
   'feat_63': 5.0642,
   'feat_64': 0.59659,
   'bankrupt': False},
  {'company_id': 12,
   'feat_1': 0.083519,
   'feat_2': 0.40286,
   'feat_3': 0.5838,
   'feat_4': 2.694,
   'feat_5': 35.966,
   'feat_6': 0.63897,
   'feat_7': 0.10728,
   'feat_8': 1.4822,
   'feat_9': 1.0475,
   'feat_10': 0.59714,
   'feat_11': 0.10728,
   'feat_12': 0.31129,
   'feat_13': 0.054553,
   'feat_14': 0.10728,
   'feat_15': 1155.2,
   'feat_16': 0.31597,
   'feat_17': 2.4822,
   'feat_18': 0.10728,
   'feat_19': 0.045977,
   'feat_20': 56.105,
   'feat_21': 0.69907,
   'feat_22': 0.09811,
   'feat_23': 0.035793,
   'feat_24': 0.79947,
   'feat_25': 0.59714,
   'feat_26': 0.25699,
   'feat_27': 0.44045,
   'feat_28': 8.1573,
   'feat_29': 3.8571,
   'feat_30': 0.11417,
   'feat_31': 0.045977,
   'feat_32': 56.473,
   'feat_33': 6.4633,
   'feat_34': 0.24353,
   'feat_35': 0.09811,
   'feat_36': 2.3426,
   'feat_37': 9.7852,
   'feat_38': 0.65536,
   'feat_39': 0.042046,
   'feat_40': 0.40927,
   'feat_41': 0.11213,
   'feat_42': 0.042046,
   'feat_43': 123.17,
   'feat_44': 67.061,
   'feat_45': 0.23286,
   'feat_46': 1.6532,
   'feat_47': 58.773,
   'feat_48': 0.078099,
   'feat_49': 0.03347,
   'feat_50': 2.3046,
   'feat_51': 0.34464,
   'feat_52': 0.15472,
   'feat_53': 8.3437,
   'feat_54': 9.1573,
   'feat_55': 4201.0,
   'feat_56': 0.045381,
   'feat_57': 0.13987,
   'feat_58': 0.95462,
   'feat_59': 0.09751,
   'feat_60': 6.5056,
   'feat_61': 5.4428,
   'feat_62': 53.91,
   'feat_63': 6.7706,
   'feat_64': 32.604,
   'bankrupt': False},
  {'company_id': 13,
   'feat_1': 0.083597,
   'feat_2': 0.19199,
   'feat_3': 0.1287,
   'feat_4': 3.6396,
   'feat_5': 105.17,
   'feat_6': 0.26136,
   'feat_7': 0.098854,
   'feat_8': 4.2085,
   'feat_9': 1.262,
   'feat_10': 0.80801,
   'feat_11': 0.098854,
   'feat_12': 2.0274,
   'feat_13': 0.29633,
   'feat_14': 0.098854,
   'feat_15': 659.63,
   'feat_16': 0.55334,
   'feat_17': 5.2085,
   'feat_18': 0.098854,
   'feat_19': 0.27573,
   'feat_20': 45.981,
   'feat_21': 0.96484,
   'feat_22': 0.075537,
   'feat_23': 0.23318,
   'feat_24': 0.30662,
   'feat_25': 0.80801,
   'feat_26': 0.47388,
   'feat_27': 2.6589,
   'feat_28': 0.15647,
   'feat_29': 5.1246,
   'feat_30': 0.53541,
   'feat_31': 0.27573,
   'feat_32': 62.645,
   'feat_33': 5.8265,
   'feat_34': 0.39343,
   'feat_35': 0.075537,
   'feat_36': 0.38294,

In [4]:
type(data)

dict

In [5]:
data.keys()

dict_keys(['schema', 'data', 'metadata'])

In [10]:
data['data']

[{'company_id': 1,
  'feat_1': 0.17419,
  'feat_2': 0.41299,
  'feat_3': 0.14371,
  'feat_4': 1.348,
  'feat_5': -28.982,
  'feat_6': 0.60383,
  'feat_7': 0.21946,
  'feat_8': 1.1225,
  'feat_9': 1.1961,
  'feat_10': 0.46359,
  'feat_11': 0.21946,
  'feat_12': 0.53139,
  'feat_13': 0.14233,
  'feat_14': 0.21946,
  'feat_15': 592.24,
  'feat_16': 0.6163,
  'feat_17': 2.4213,
  'feat_18': 0.21946,
  'feat_19': 0.12272,
  'feat_20': 37.573,
  'feat_21': 0.9969,
  'feat_22': 0.2951,
  'feat_23': 0.097402,
  'feat_24': 0.75641,
  'feat_25': 0.46359,
  'feat_26': 0.50669,
  'feat_27': 1.9737,
  'feat_28': 0.32417,
  'feat_29': 5.9473,
  'feat_30': 0.22493,
  'feat_31': 0.12272,
  'feat_32': 100.82,
  'feat_33': 3.6203,
  'feat_34': 0.71453,
  'feat_35': 0.2951,
  'feat_36': 1.8079,
  'feat_37': 123140.0,
  'feat_38': 0.46359,
  'feat_39': 0.16501,
  'feat_40': 0.21282,
  'feat_41': 0.041124,
  'feat_42': 0.16501,
  'feat_43': 95.682,
  'feat_44': 58.109,
  'feat_45': 0.94621,
  'feat_46': 0.90221,
  'feat_47': 44.941,
  'feat_48': 0.26003,
  'feat_49': 0.1454,
  'feat_50': 1.348,
  'feat_51': 0.41299,
  'feat_52': 0.27622,
  'feat_53': 1.0457,
  'feat_54': 1.0458,
  'feat_55': 127280.0,
  'feat_56': 0.16396,
  'feat_57': 0.37574,
  'feat_58': 0.83604,
  'feat_59': 6.5269e-06,
  'feat_60': 9.7145,
  'feat_61': 6.2813,
  'feat_62': 84.291,
  'feat_63': 4.3303,
  'feat_64': 4.0341,
  'bankrupt': False},
 {'company_id': 2,
  'feat_1': 0.14624,
  'feat_2': 0.46038,
  'feat_3': 0.2823,
  'feat_4': 1.6294,
  'feat_5': 2.5952,
  'feat_6': 0.0,
  'feat_7': 0.17185,
  'feat_8': 1.1721,
  'feat_9': 1.6018,
  'feat_10': 0.53962,
  'feat_11': 0.17579,
  'feat_12': 0.38317,
  'feat_13': 0.12647,
  'feat_14': 0.17185,
  'feat_15': 829.46,
  'feat_16': 0.44004,
  'feat_17': 2.1721,
  'feat_18': 0.17185,
  'feat_19': 0.10728,
  'feat_20': 60.954,
  'feat_21': 5.0889,
  'feat_22': 0.17571,
  'feat_23': 0.091295,
  'feat_24': None,
  'feat_25': 0.17523,
  'feat_26': 0.38442,
  'feat_27': 44.593,
  'feat_28': 1.0486,
  'feat_29': 4.0792,
  'feat_30': 0.24384,
  'feat_31': 0.10974,
  'feat_32': 105.09,
  'feat_33': 3.4733,
  'feat_34': 3.3836,
  'feat_35': 0.044076,
  'feat_36': 1.6018,
  'feat_37': None,
  'feat_38': 0.53962,
  'feat_39': 0.027516,
  'feat_40': 0.16406,
  'feat_41': 0.074333,
  'feat_42': 0.10969,
  'feat_43': 149.75,
  'feat_44': 88.801,
  'feat_45': 0.54669,
  'feat_46': 1.033,
  'feat_47': 62.678,
  'feat_48': 0.14497,
  'feat_49': 0.090503,
  'feat_50': 1.5874,
  'feat_51': 0.44849,
  'feat_52': 0.28791,
  'feat_53': 2.0044,
  'feat_54': 2.0044,
  'feat_55': 3387.8,
  'feat_56': 0.027516,
  'feat_57': 0.271,
  'feat_58': 0.90108,
  'feat_59': 0.0,
  'feat_60': 5.9882,
  'feat_61': 4.1103,
  'feat_62': 102.19,
  'feat_63': 3.5716,
  'feat_64': 5.95,
  'bankrupt': False},
 {'company_id': 3,
  'feat_1': 0.00059529,
  'feat_2': 0.22612,
  'feat_3': 0.48839,
  'feat_4': 3.1599,
  'feat_5': 84.874,
  'feat_6': 0.19114,
  'feat_7': 0.0045718,
  'feat_8': 2.9881,
  'feat_9': 1.0077,
  'feat_10': 0.67566,
  'feat_11': 0.0045718,
  'feat_12': 0.020219,
  'feat_13': 0.030966,
  'feat_14': 0.0045718,
  'feat_15': 2094.1,
  'feat_16': 0.1743,
  'feat_17': 4.4225,
  'feat_18': 0.0045718,
  'feat_19': 0.0035921,
  'feat_20': 53.881,
  'feat_21': 0.67451,
  'feat_22': 0.04061,
  'feat_23': 0.00046772,
  'feat_24': 0.2347,
  'feat_25': 0.67566,
  'feat_26': 0.15672,
  'feat_27': 0.32153,
  'feat_28': 1.7107,
  'feat_29': 4.622,
  'feat_30': 0.036196,
  'feat_31': 0.0035921,
  'feat_32': 65.345,
  'feat_33': 5.5857,
  'feat_34': 0.1796,
  'feat_35': 0.04061,
  'feat_36': 1.3425,
  'feat_37': None,
  'feat_38': 0.67566,
  'feat_39': 0.031907,
  'feat_40': 0.84469,
  'feat_41': 0.098528,
  'feat_42': 0.031907,
  'feat_43': 150.13,
  'feat_44': 96.251,
  'feat_45': 0.0031684,
  'feat_46': 2.329,
  'feat_47': 54.296,
  'feat_48': 0.0057691,
  'feat_49': 0.0045328,
  'feat_50': 3.1599,
  'feat_51': 0.22612,
  'feat_52': 0.17903,
  'feat_53': 2.3667,
  'feat_54': 2.3667,
  'feat_55': 20453.0,
  'feat_56': 0.0076387,
  'feat_57': 0.00088105,
  'feat_58': 0.99236,
  'feat_59': 0.0,
  'feat_60': 6.7742,
  'feat_61': 3.7922,
  'feat_62': 64.846,
  'feat_63': 5.6287,
  'feat_64': 4.4581,
  'bankrupt': False},
 {'company_id': 5,
  'feat_1': 0.18829,
  'feat_2': 0.41504,
  'feat_3': 0.34231,
  'feat_4': 1.9279,
  'feat_5': -58.274,
  'feat_6': 0.0,
  'feat_7': 0.23358,
  'feat_8': 1.4094,
  'feat_9': 1.3393,
  'feat_10': 0.58496,
  'feat_11': 0.23881,
  'feat_12': 0.63317,
  'feat_13': 0.1878,
  'feat_14': 0.23358,
  'feat_15': 602.31,
  'feat_16': 0.606,
  'feat_17': 2.4094,
  'feat_18': 0.23358,
  'feat_19': 0.17441,
  'feat_20': 140.86,
  'feat_21': 1.2039,
  'feat_22': 0.23493,
  'feat_23': 0.14059,
  'feat_24': 0.0,
  'feat_25': 0.5725,
  'feat_26': 0.49687,
  'feat_27': 44.947,
  'feat_28': 1.1853,
  'feat_29': 4.6033,
  'feat_30': 0.30691,
  'feat_31': 0.17784,
  'feat_32': 122.09,
  'feat_33': 2.9897,
  'feat_34': 2.6574,
  'feat_35': 0.23635,
  'feat_36': 1.3393,
  'feat_37': 4.549,
  'feat_38': 0.62769,
  'feat_39': 0.17648,
  'feat_40': 0.013769,
  'feat_41': 0.054712,
  'feat_42': 0.17542,
  'feat_43': 192.45,
  'feat_44': 51.585,
  'feat_45': 0.36429,
  'feat_46': 0.52685,
  'feat_47': 171.05,
  'feat_48': 0.21699,
  'feat_49': 0.16203,
  'feat_50': 1.7136,
  'feat_51': 0.36891,
  'feat_52': 0.33449,
  'feat_53': 2.0256,
  'feat_54': 2.1735,
  'feat_55': 13730.0,
  'feat_56': 0.17648,
  'feat_57': 0.32188,
  'feat_58': 0.82635,
  'feat_59': 0.073039,
  'feat_60': 2.5912,
  'feat_61': 7.0756,
  'feat_62': 100.54,
  'feat_63': 3.6303,
  'feat_64': 4.6375,
  'bankrupt': False},
 {'company_id': 6,
  'feat_1': 0.18206,
  'feat_2': 0.55615,
  'feat_3': 0.32191,
  'feat_4': 1.6045,
  'feat_5': 16.314,
  'feat_6': 0.0,
  'feat_7': 0.18206,
  'feat_8': 0.79808,
  'feat_9': 1.8126,
  'feat_10': 0.44385,
  'feat_11': 0.20766,
  'feat_12': 0.34188,
  'feat_13': 0.27163,
  'feat_14': 0.18206,
  'feat_15': 412.3,
  'feat_16': 0.88528,
  'feat_17': 1.7981,
  'feat_18': 0.18206,
  'feat_19': 0.10045,
  'feat_20': 43.168,
  'feat_21': 1.2724,
  'feat_22': 0.0,
  'feat_23': 0.10045,
  'feat_24': None,
  'feat_25': 0.416,
  'feat_26': 0.88528,
  'feat_27': 0.0,
  'feat_28': 2.2118,
  'feat_29': 3.8104,
  'feat_30': 0.29926,
  'feat_31': 0.22877,
  'feat_32': 241.41,
  'feat_33': 1.512,
  'feat_34': 1.4478,
  'feat_35': 0.029538,
  'feat_36': 1.8126,
  'feat_37': 49.017,
  'feat_38': 0.45691,
  'feat_39': 0.016296,
  'feat_40': 0.1856,
  'feat_41': 0.059746,
  'feat_42': 0.0,
  'feat_43': 152.16,
  'feat_44': 108.99,
  'feat_45': 0.8493,
  'feat_46': 1.2019,
  'feat_47': 97.177,
  'feat_48': -0.31028,
  'feat_49': -0.17119,
  'feat_50': 1.5364,
  'feat_51': 0.53254,
  'feat_52': 0.6614,
  'feat_53': 3.0496,
  'feat_54': 3.1393,
  'feat_55': 2080.6,
  'feat_56': 0.55577,
  'feat_57': 0.41019,
  'feat_58': 0.46957,
  'feat_59': 0.029421,
  'feat_60': 8.4553,
  'feat_61': 3.3488,
  'feat_62': 107.24,
  'feat_63': 3.4036,
  'feat_64': 12.454,
  'bankrupt': False},
 {'company_id': 7,
  'feat_1': 0.11503,
  'feat_2': 0.036659,
  'feat_3': 0.92345,
  'feat_4': 112.63,
  'feat_5': 55.58,
  'feat_6': 0.0,
  'feat_7': 0.14215,
  'feat_8': 26.279,
  'feat_9': 0.44339,
  'feat_10': 0.96334,
  'feat_11': 0.1435,
  'feat_12': 17.183,
  'feat_13': 0.32533,
  'feat_14': 0.14215,
  'feat_15': 92.759,
  'feat_16': 3.9349,
  'feat_17': 27.279,
  'feat_18': 0.14215,
  'feat_19': 0.32061,
  'feat_20': 19.801,
  'feat_21': 0.82872,
  'feat_22': 0.082265,
  'feat_23': 0.25943,
  'feat_24': 10.573,
  'feat_25': 0.96082,
  'feat_26': 3.195,
  'feat_27': 61.21,
  'feat_28': 13.526,
  'feat_29': 4.339,
  'feat_30': -0.055356,
  'feat_31': 0.32222,
  'feat_32': 7.2995,
  'feat_33': 50.003,
  'feat_34': 11.284,
  'feat_35': 0.029724,
  'feat_36': 0.44339,
  'feat_37': 58.907,
  'feat_38': 0.97875,
  'feat_39': 0.067038,
  'feat_40': 108.44,
  'feat_41': 0.014485,
  'feat_42': 0.18554,
  'feat_43': 28.536,
  'feat_44': 8.7355,
  'feat_45': 4.7821,
  'feat_46': 109.72,
  'feat_47': 21.224,
  'feat_48': 0.080169,
  'feat_49': 0.18081,
  'feat_50': 25.416,
  'feat_51': 0.0082728,
  'feat_52': 0.019999,
  'feat_53': 14.11,
  'feat_54': 14.336,
  'feat_55': 20158.0,
  'feat_56': 0.067038,
  'feat_57': 0.1194,
  'feat_58': 0.75777,
  'feat_59': 0.015995,
  'feat_60': 18.433,
  'feat_61': 41.783,
  'feat_62': 6.8102,
  'feat_63': 53.596,
  'feat_64': 6.4942,
  'bankrupt': False},
 {'company_id': 8,
  'feat_1': 0.0098323,
  'feat_2': 0.67066,
  'feat_3': 0.13546,
  'feat_4': 1.2393,
  'feat_5': -107.73,
  'feat_6': -0.0014006,
  'feat_7': 0.013422,
  'feat_8': 0.49108,
  'feat_9': 1.1825,
  'feat_10': 0.32934,
  'feat_11': 0.055717,
  'feat_12': 0.023711,
  'feat_13': 0.047491,
  'feat_14': 0.013422,
  'feat_15': 4359.1,
  'feat_16': 0.083733,
  'feat_17': 1.4911,
  'feat_18': 0.013422,
  'feat_19': 0.011351,
  'feat_20': 44.614,
  'feat_21': 1.013,
  'feat_22': 0.04612,
  'feat_23': 0.0083151,
  'feat_24': 0.0,
  'feat_25': 0.3105,
  'feat_26': 0.078381,
  'feat_27': 1.0904,
  'feat_28': 0.45384,
  'feat_29': 5.9673,
  'feat_30': 0.56717,
  'feat_31': 0.011351,
  'feat_32': 217.81,
  'feat_33': 1.7455,
  'feat_34': 1.4733,
  'feat_35': 0.23389,
  'feat_36': 1.1825,
  'feat_37': 11.749,
  'feat_38': 0.37675,
  'feat_39': 0.1978,
  'feat_40': 0.46285,
  'feat_41': 0.25159,
  'feat_42': 0.039003,
  'feat_43': 135.67,
  'feat_44': 91.058,
  'feat_45': 0.068029,
  'feat_46': 0.98398,
  'feat_47': 53.392,
  'feat_48': 0.0033856,
  'feat_49': 0.0028632,
  'feat_50': 1.046,
  'feat_51': 0.56606,
  'feat_52': 0.57291,
  'feat_53': 1.1034,
  'feat_54': 1.2622,
  'feat_55': 1.2393,
  'feat_56': 0.1978,
  'feat_57': 0.029854,
  'feat_58': 0.83478,
  'feat_59': 0.14394,
  'feat_60': 8.1813,
  'feat_61': 4.0084,
  'feat_62': 174.73,
  'feat_63': 2.0889,
  'feat_64': 3.9616,
  'bankrupt': False},
 {'company_id': 9,
  'feat_1': 0.23895,
  'feat_2': 0.55473,
  'feat_3': 0.40697,
  'feat_4': 1.7609,
  'feat_5': -22.907,
  'feat_6': 0.0,
  'feat_7': 0.29714,
  'feat_8': 0.80268,
  'feat_9': 2.3317,
  'feat_10': 0.44527,
  'feat_11': 0.33061,
  'feat_12': 0.55553,
  'feat_13': 0.13198,
  'feat_14': 0.29714,
  'feat_15': 657.95,
  'feat_16': 0.55475,
  'feat_17': 1.8027,
  'feat_18': 0.29714,
  'feat_19': 0.12743,
  'feat_20': 81.972,
  'feat_21': 1.0467,
  'feat_22': 0.33015,
  'feat_23': 0.10248,
  'feat_24': None,
  'feat_25': 0.43913,
  'feat_26': 0.44985,
  'feat_27': 9.8633,
  'feat_28': 6.9983,
  'feat_29': 3.911,
  'feat_30': 0.20211,
  'feat_31': 0.13836,
  'feat_32': 97.4,
  'feat_33': 3.7474,
  'feat_34': 3.6133,
  'feat_35': 0.32732,
  'feat_36': 2.3317,
  'feat_37': 21.065,
  'feat_38': 0.46512,
  'feat_39': 0.14038,
  'feat_40': 0.17507,
  'feat_41': 0.054265,
  'feat_42': 0.14159,
  'feat_43': 132.77,
  'feat_44': 50.802,
  'feat_45': 0.4563,
  'feat_46': 0.78182,
  'feat_47': 95.359,
  'feat_48': 0.31955,
  'feat_49': 0.13704,
  'feat_50': 1.6978,
  'feat_51': 0.53488,
  'feat_52': 0.26685,
  'feat_53': 7.6569,
  'feat_54': 7.9983,
  'feat_55': 3315.2,
  'feat_56': 0.14038,
  'feat_57': 0.53663,
  'feat_58': 0.87292,
  'feat_59': 0.044584,
  'feat_60': 4.4527,
  'feat_61': 7.1847,
  'feat_62': 83.727,
  'feat_63': 4.3594,
  'feat_64': 40.097,
  'bankrupt': False},
 {'company_id': 10,
  'feat_1': -0.11986,
  'feat_2': 0.60733,
  'feat_3': 0.041368,
  'feat_4': 1.0688,
  'feat_5': -37.595,
  'feat_6': -0.44797,
  'feat_7': -0.11986,
  'feat_8': 0.64655,
  'feat_9': 3.0,
  'feat_10': 0.39267,
  'feat_11': -0.11986,
  'feat_12': -0.1993,
  'feat_13': 0.011424,
  'feat_14': -0.11986,
  'feat_15': 6467.9,
  'feat_16': 0.056432,
  'feat_17': 1.6466,
  'feat_18': -0.11986,
  'feat_19': -0.039953,
  'feat_20': 28.419,
  'feat_21': 0.858,
  'feat_22': 0.0,
  'feat_23': -0.039953,
  'feat_24': None,
  'feat_25': -0.52078,
  'feat_26': 0.056432,
  'feat_27': None,
  'feat_28': 0.11581,
  'feat_29': 3.3322,
  'feat_30': 0.19386,
  'feat_31': -0.079906,
  'feat_32': 99.456,
  'feat_33': 3.67,
  'feat_34': 3.6342,
  'feat_35': 0.0069493,
  'feat_36': 3.0,
  'feat_37': None,
  'feat_38': 0.39267,
  'feat_39': 0.0023164,
  'feat_40': 0.079719,
  'feat_41': 0.13134,
  'feat_42': 0.0,
  'feat_43': 72.372,
  'feat_44': 43.953,
  'feat_45': -0.51315,
  'feat_46': 0.6804,
  'feat_47': 38.627,
  'feat_48': -0.15413,
  'feat_49': -0.051377,
  'feat_50': 1.0584,
  'feat_51': 0.60142,
  'feat_52': 0.27248,
  'feat_53': 1.0993,
  'feat_54': 1.0993,
  'feat_55': 88.899,
  'feat_56': 0.26428,
  'feat_57': -0.30525,
  'feat_58': 0.73749,
  'feat_59': 0.0,
  'feat_60': 12.844,
  'feat_61': 8.3043,
  'feat_62': 73.172,
  'feat_63': 4.9883,
  'feat_64': 8.3984,
  'bankrupt': False},
 {'company_id': 11,
  'feat_1': -0.13035,
  'feat_2': 0.08968,
  'feat_3': 0.14907,
  'feat_4': 2.6622,
  'feat_5': -34.003,
  'feat_6': -0.20856,
  'feat_7': -0.12478,
  'feat_8': 8.9791,
  'feat_9': 0.76134,
  'feat_10': 0.80524,
  'feat_11': -0.12478,
  'feat_12': -1.3914,
  'feat_13': -0.025158,
  'feat_14': -0.12478,
  'feat_15': -2864.9,
  'feat_16': -0.12741,
  'feat_17': 11.151,
  'feat_18': -0.12478,
  'feat_19': -0.27475,
  'feat_20': 148.05,
  'feat_21': 0.68266,
  'feat_22': -0.12461,
  'feat_23': -0.28701,
  'feat_24': -0.19542,
  'feat_25': 0.80524,
  'feat_26': -0.18946,
  'feat_27': -2.0889,
  'feat_28': 0.19582,
  'feat_29': 4.0259,
  'feat_30': 0.18671,
  'feat_31': -0.27475,
  'feat_32': 54.873,
  'feat_33': 6.6517,
  'feat_34': -1.3895,
  'feat_35': -0.12461,
  'feat_36': 0.50197,
  'feat_37': None,
  'feat_38': 0.80524,
  'feat_39': -0.27437,
  'feat_40': 0.17146,
  'feat_41': -0.26207,
  'feat_42': -0.27437,
  'feat_43': 179.52,
  'feat_44': 31.473,
  'feat_45': -0.70761,
  'feat_46': 0.60813,
  'feat_47': 112.71,
  'feat_48': -0.23796,
  'feat_49': -0.52396,
  'feat_50': 2.6622,
  'feat_51': 0.08968,
  'feat_52': 0.15034,
  'feat_53': 1.0578,
  'feat_54': 1.0578,
  'feat_55': 1582.1,
  'feat_56': -0.31347,
  'feat_57': -0.16187,
  'feat_58': 1.3135,
  'feat_59': 0.0,
  'feat_60': 2.4655,
  'feat_61': 11.597,
  'feat_62': 72.074,
  'feat_63': 5.0642,
  'feat_64': 0.59659,
  'bankrupt': False},
 {'company_id': 12,
  'feat_1': 0.083519,
  'feat_2': 0.40286,
  'feat_3': 0.5838,
  'feat_4': 2.694,
  'feat_5': 35.966,
  'feat_6': 0.63897,
  'feat_7': 0.10728,
  'feat_8': 1.4822,
  'feat_9': 1.0475,
  'feat_10': 0.59714,
  'feat_11': 0.10728,
  'feat_12': 0.31129,
  'feat_13': 0.054553,
  'feat_14': 0.10728,
  'feat_15': 1155.2,
  'feat_16': 0.31597,
  'feat_17': 2.4822,
  'feat_18': 0.10728,
  'feat_19': 0.045977,
  'feat_20': 56.105,
  'feat_21': 0.69907,
  'feat_22': 0.09811,
  'feat_23': 0.035793,
  'feat_24': 0.79947,
  'feat_25': 0.59714,
  'feat_26': 0.25699,
  'feat_27': 0.44045,
  'feat_28': 8.1573,
  'feat_29': 3.8571,
  'feat_30': 0.11417,
  'feat_31': 0.045977,
  'feat_32': 56.473,
  'feat_33': 6.4633,
  'feat_34': 0.24353,
  'feat_35': 0.09811,
  'feat_36': 2.3426,
  'feat_37': 9.7852,
  'feat_38': 0.65536,
  'feat_39': 0.042046,
  'feat_40': 0.40927,
  'feat_41': 0.11213,
  'feat_42': 0.042046,
  'feat_43': 123.17,
  'feat_44': 67.061,
  'feat_45': 0.23286,
  'feat_46': 1.6532,
  'feat_47': 58.773,
  'feat_48': 0.078099,
  'feat_49': 0.03347,
  'feat_50': 2.3046,
  'feat_51': 0.34464,
  'feat_52': 0.15472,
  'feat_53': 8.3437,
  'feat_54': 9.1573,
  'feat_55': 4201.0,
  'feat_56': 0.045381,
  'feat_57': 0.13987,
  'feat_58': 0.95462,
  'feat_59': 0.09751,
  'feat_60': 6.5056,
  'feat_61': 5.4428,
  'feat_62': 53.91,
  'feat_63': 6.7706,
  'feat_64': 32.604,
  'bankrupt': False},
 {'company_id': 13,
  'feat_1': 0.083597,
  'feat_2': 0.19199,
  'feat_3': 0.1287,
  'feat_4': 3.6396,
  'feat_5': 105.17,
  'feat_6': 0.26136,
  'feat_7': 0.098854,
  'feat_8': 4.2085,
  'feat_9': 1.262,
  'feat_10': 0.80801,
  'feat_11': 0.098854,
  'feat_12': 2.0274,
  'feat_13': 0.29633,
  'feat_14': 0.098854,
  'feat_15': 659.63,
  'feat_16': 0.55334,
  'feat_17': 5.2085,
  'feat_18': 0.098854,
  'feat_19': 0.27573,
  'feat_20': 45.981,
  'feat_21': 0.96484,
  'feat_22': 0.075537,
  'feat_23': 0.23318,
  'feat_24': 0.30662,
  'feat_25': 0.80801,
  'feat_26': 0.47388,
  'feat_27': 2.6589,
  'feat_28': 0.15647,
  'feat_29': 5.1246,
  'feat_30': 0.53541,
  'feat_31': 0.27573,
  'feat_32': 62.645,
  'feat_33': 5.8265,
  'feat_34': 0.39343,
  'feat_35': 0.075537,
  'feat_36': 0.38294,
  'feat_37': 0.92361,
  'feat_38': 0.95124,
  'feat_39': 0.21069,
  'feat_40': 0.056287,
  'feat_41': 0.076122,
  'feat_42': 0.21069,
  'feat_43': 177.87,
  'feat_44': 131.89,
  'feat_45': 1.851,
  'feat_46': 2.7133,
  'feat_47': 58.027,
  'feat_48': 0.068152,
  'feat_49': 0.1901,
  'feat_50': 0.92429,
  'feat_51': 0.048758,
  'feat_52': 0.17163,
  'feat_53': 0.98233,
  'feat_54': 1.1565,
  'feat_55': 17148.0,
  'feat_56': 0.2076,
  'feat_57': 0.10346,
  'feat_58': 0.7924,
  'feat_59': 0.17727,
  'feat_60': 7.9381,
  'feat_61': 2.7674,
  'feat_62': 49.64,
  'feat_63': 7.3529,
  'feat_64': 0.43586,
  'bankrupt': False},
 {'company_id': 14,
  'feat_1': 0.081951,
  'feat_2': 0.24608,
  'feat_3': 0.31273,
  'feat_4': 3.5654,
  'feat_5': 29.45,
  'feat_6': 0.011692,
  'feat_7': 0.094949,
  'feat_8': 3.0638,
  'feat_9': 1.1117,
  'feat_10': 0.75392,
  'feat_11': 0.094949,
  'feat_12': 0.77888,
  'feat_13': 0.13768,
  'feat_14': 0.094949,
  'feat_15': 762.7,
  'feat_16': 0.47856,
  'feat_17': 4.0638,
  'feat_18': 0.094949,
  'feat_19': 0.11101,
  'feat_20': 90.694,
  'feat_21': 1.2354,
  'feat_22': 0.090144,
  'feat_23': 0.095813,
  'feat_24': 0.024163,
  'feat_25': 0.75392,
  'feat_26': 0.42574,
  'feat_27': 1.1717,
  'feat_28': 0.55316,
  'feat_29': 4.8684,
  'feat_30': 0.2118,
  'feat_31': 0.11101,
  'feat_32': 57.834,
  'feat_33': 6.3111,
  'feat_34': 0.36632,
  'feat_35': 0.090144,
  'feat_36': 0.86431,
  'feat_37': 1.7887,
  'feat_38': 0.87809,
  'feat_39': 0.10539,
  'feat_40': 0.85355,
  'feat_41': 0.071621,
  'feat_42': 0.10539,
  'feat_43': 141.07,
  'feat_44': 50.38,
  'feat_45': 0.3856,
  'feat_46': 1.822,
  'feat_47': 100.83,
  'feat_48': 0.06733,
  'feat_49': 0.078718,
  'feat_50': 1.7663,
  'feat_51': 0.12191,
  'feat_52': 0.15845,
  'feat_53': 1.3335,
  'feat_54': 1.5532,
  'feat_55': 23101.0,
  'feat_56': 0.10051,
  'feat_57': 0.1087,
  'feat_58': 0.89949,
  'feat_59': 0.1647,
  'feat_60': 4.0245,
  'feat_61': 7.2449,
  'feat_62': 52.022,
  'feat_63': 7.0163,
  'feat_64': 1.5129,
  'bankrupt': False},
 {'company_id': 15,
  'feat_1': -0.20878,
  'feat_2': 1.0024,
  'feat_3': -0.38957,
  'feat_4': 0.57408,
  'feat_5': -253.85,
  'feat_6': -0.20143,
  'feat_7': -0.20878,
  'feat_8': -0.0024414,
  'feat_9': 1.0536,
  'feat_10': -0.0024473,
  'feat_11': -0.18972,
  'feat_12': -0.22826,
  'feat_13': -0.13894,
  'feat_14': -0.20878,
  'feat_15': -2499.6,
  'feat_16': -0.14602,
  'feat_17': 0.99756,
  'feat_18': -0.20878,
  'feat_19': -0.19816,
  'feat_20': 39.001,
  'feat_21': None,
  'feat_22': 3.9826e-05,
  'feat_23': -0.19816,
  'feat_24': None,
  'feat_25': -0.29253,
  'feat_26': -0.14602,
  'feat_27': 0.0020897,
  'feat_28': -0.8203,
  'feat_29': 4.2278,
  'feat_30': 0.92155,
  'feat_31': -0.44219,
  'feat_32': 393.18,
  'feat_33': 0.92833,
  'feat_34': 0.84703,
  'feat_35': 0.079156,
  'feat_36': 1.0536,
  'feat_37': 18.673,
  'feat_38': 0.019645,
  'feat_39': 0.075132,
  'feat_40': 0.091979,
  'feat_41': 0.53518,
  'feat_42': 3.7802e-05,
  'feat_43': 152.77,
  'feat_44': 113.77,
  'feat_45': -1.8546,
  'feat_46': 0.45101,
  'feat_47': 48.392,
  'feat_48': -0.062357,
  'feat_49': -0.059187,
  'feat_50': 0.52381,
  'feat_51': 0.91466,
  'feat_52': 1.0772,
  'feat_53': -0.0051533,
  'feat_54': 0.041365,
  'feat_55': -6583.1,
  'feat_56': 0.19406,
  'feat_57': 85.308,
  'feat_58': 0.83631,
  'feat_59': -9.0269,
  'feat_60': 9.3588,
  'feat_61': 3.2083,
  'feat_62': 316.88,
  'feat_63': 1.1519,
  'feat_64': 2.2185,
  'bankrupt': False},
 {'company_id': 16,
  'feat_1': 0.0138,
  'feat_2': 0.87373,
  'feat_3': -0.11986,
  'feat_4': 0.86281,
  'feat_5': -125.35,

In [15]:
df = pd.DataFrame(data['data']).set_index("company_id")
df.head()

,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,feat_10,...,feat_56,feat_57,feat_58,feat_59,feat_60,feat_61,feat_62,feat_63,feat_64,bankrupt
company_id,,,,,,,,,,,,,,,,,,,,,
1,0.174190,0.41299,0.14371,1.3480,-28.9820,0.60383,0.219460,1.12250,1.1961,0.46359,...,0.163960,0.375740,0.83604,0.000007,9.7145,6.2813,84.291,4.3303,4.0341,False
2,0.146240,0.46038,0.28230,1.6294,2.5952,0.00000,0.171850,1.17210,1.6018,0.53962,...,0.027516,0.271000,0.90108,0.000000,5.9882,4.1103,102.190,3.5716,5.9500,False
3,0.000595,0.22612,0.48839,3.1599,84.8740,0.19114,0.004572,2.98810,1.0077,0.67566,...,0.007639,0.000881,0.99236,0.000000,6.7742,3.7922,64.846,5.6287,4.4581,False
5,0.188290,0.41504,0.34231,1.9279,-58.2740,0.00000,0.233580,1.40940,1.3393,0.58496,...,0.176480,0.321880,0.82635,0.073039,2.5912,7.0756,100.540,3.6303,4.6375,False
6,0.182060,0.55615,0.32191,1.6045,16.3140,0.00000,0.182060,0.79808,1.8126,0.44385,...,0.555770,0.410190,0.46957,0.029421,8.4553,3.3488,107.240,3.4036,12.4540,False

# **Working with SQL Databases**

A database is a collection of interrelated data. The primary goal of a database is to store and retrieve information in a convenient and efficient way. There are many types of databases. A **relational database**. A relational database is a widely used database model that consists of a collection of uniquely named **tables** used to store information. The structure of a database model with its tables, constraints, and relationships is called a **schema**. 

A Structured Query Language (**SQL**), is used to retrieve information from a relational database. SQL is one of the most commonly used database languages. It allows data stored in a relational database to be queried, modified, and manipulated easily with basic commands. SQL powers database engines like MySQL, SQL Server, SQLite, and PostgreSQL. The examples and projects in this course will use SQLite. 

A **table** refers to a collection of rows and columns in a relational database. When reading data into a pandas DataFrame, an **index** can be defined, which acts as the label for every row in the DataFrame.

### ipython-sql

`ipython-sql` allows you to write SQL code directly in a Jupyter Notebook. The `%sql` (or `%%sql`) magic command is added to the beginning of a code block and then SQL code can be written.

### Connecting with ipython-sql

We can connect to a database using the %sql magic function:

In [1]:
#import sqlite3
%load_ext sql
%config SqlMagic.style = '_DEPRECATED_DEFAULT'
from sqlalchemy import create_engine

# Querying a Database

## Building Blocks of the Basic Query

There are six common clauses used for querying data:
   
| Clause Name | Definition | 
| --- | --- | 
| `SELECT` | Determines which columns to include in the query's result |
| `FROM` | Identifies the table from which to query the data from |
| `WHERE` | filters data |
| `GROUP BY` | groups rows by common values in columns |
| `HAVING` | filters out unwanted groups from GROUP BY |
| `ORDER BY` | Orders the rows using one or more columns |
| `LIMIT` | Outputs the specified number of rows |

All clauses may be used together, but `SELECT` and `FROM` are the only required clauses. The format of clauses is in the example query below:

```sql
SELECT column1, column2
FROM table_name
WHERE "conditions"
GROUP BY "column-list"
HAVING "conditions"
ORDER BY "column-list"
```

In [16]:
engine = create_engine("postgresql+psycopg://datalab:datalab@localhost:5432/nepal")

In [2]:
%sql postgresql+psycopg://datalab:datalab@localhost:5432/nepal

In [3]:
%%sql
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema NOT IN ('pg_catalog', 'information_schema')

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
4 rows affected.

[('public', 'building_structure'),
 ('public', 'building_damage'),
 ('public', 'household_demographics'),
 ('public', 'id_map')]

In [11]:
pd.read_sql("""
    SELECT table_schema, table_name
    FROM information_schema.tables
    WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
""", engine)

  table_schema              table_name
0       public      building_structure
1       public         building_damage
2       public  household_demographics
3       public                  id_map

## Filtering and Sorting Data

SQL provides a variety of comparison operators that can be used with the WHERE clause to filter the data. 


| Comparison Operator | Description | 
| --- | --- | 
| = | Equal |
| > | Greater than |
| < | Less than|
| >= | Greater than or equal to |
| <= | Less than or equal to |
| <> or != | Not equal to |
| LIKE | String comparison test |

For example, to select the first 5 homes in Ramechhap (district `2`):

In [5]:
%%sql
SELECT COUNT(*) AS Num_Rows
FROM id_map

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(249932,)]

In [6]:
%%sql
SELECT DISTINCT(district_id)
FROM id_map

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
4 rows affected.

[(1,), (2,), (3,), (4,)]

In [7]:
%%sql
SELECT COUNT(DISTINCT(building_id))
FROM id_map

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(234835,)]

In [8]:
%%sql
SELECT *
FROM id_map
WHERE district_id = 4
LIMIT 5

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
5 rows affected.

[(16400001, 164000, 38, 4),
 (16400101, 164001, 38, 4),
 (16400201, 164002, 38, 4),
 (16400301, 164003, 38, 4),
 (16400401, 164004, 38, 4)]

In [9]:
%%sql
SELECT COUNT(*)
FROM id_map
WHERE district_id = 4

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(75883,)]

In [10]:
%%sql
SELECT COUNT(DISTINCT(BUILDING_ID)) AS Num_Building
FROM id_map
WHERE district_id = 4

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(70836,)]

In [11]:
%%sql
SELECT *
FROM building_structure
limit 5;

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
5 rows affected.

[(1, 1, 1, 9, 288, 9, 9, 'Flat', 'Other', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar'),
 (2, 1, 1, 15, 364, 9, 9, 'Flat', 'Other', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar'),
 (3, 1, 1, 20, 384, 9, 9, 'Flat', 'Other', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar'),
 (4, 1, 1, 20, 312, 9, 9, 'Flat', 'Other', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar'),
 (5, 1, 1, 30, 308, 9, 9, 'Flat', 'Other', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar')]

In [12]:
%%sql
SELECT COUNT(*) AS Num_Building
FROM building_structure

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(234835,)]

In [13]:
%%sql
SELECT COUNT(*)
FROM id_map AS i
JOIN building_structure AS b
ON i.building_id = b.building_id
WHERE district_id = 4
LIMIT 5

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
1 rows affected.

[(75883,)]

In [14]:
%%sql
SELECT DISTINCT(i.building_id), 
        b.*
FROM id_map AS i
JOIN building_structure AS b
ON i.building_id = b.building_id
WHERE district_id = 4
LIMIT 5

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
5 rows affected.

[(164000, 164000, 1, 0, 40, 336, 6, 0, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Rubble unclear', 'Stone, mud mortar'),
 (164001, 164001, 2, 2, 12, 420, 13, 13, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar'),
 (164002, 164002, 3, 3, 20, 560, 18, 18, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar'),
 (164003, 164003, 2, 2, 15, 390, 12, 12, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar'),
 (164004, 164004, 2, 2, 15, 290, 13, 13, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Square', 'Damaged-Not used', 'Stone, mud mortar')]

In [15]:
%%sql
SELECT DISTINCT(i.building_id) AS b_id, 
        b.*,
        bd.damage_grade
FROM id_map AS i
JOIN building_structure AS b
ON i.building_id = b.building_id
JOIN building_damage AS bd
ON bd.building_id = b.building_id
WHERE district_id = 4
LIMIT 5

 * postgresql+psycopg://datalab:***@localhost:5432/nepal
5 rows affected.

[(164000, 164000, 1, 0, 40, 336, 6, 0, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'Not applicable', 'Not attached', 'Rectangular', 'Damaged-Rubble unclear', 'Stone, mud mortar', 'Grade 5'),
 (164001, 164001, 2, 2, 12, 420, 13, 13, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar', 'Grade 3'),
 (164002, 164002, 3, 3, 20, 560, 18, 18, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Repaired and used', 'Stone, mud mortar', 'Grade 2'),
 (164003, 164003, 2, 2, 15, 390, 12, 12, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Rectangular', 'Damaged-Used in risk', 'Stone, mud mortar', 'Grade 4'),
 (164004, 164004, 2, 2, 15, 290, 13, 13, 'Flat', 'Mud mortar-Stone/Brick', 'Bamboo/Timber-Light roof', 'Mud', 'TImber/Bamboo-Mud', 'Not attached', 'Square', 'Damaged-Not used', 'Stone, mud mortar', 'Grade 4')]

In [17]:
query = """
        SELECT DISTINCT(i.building_id) AS b_id, 
        b.*,
        bd.damage_grade
        FROM id_map AS i
        JOIN building_structure AS b
        ON i.building_id = b.building_id
        JOIN building_damage AS bd
        ON bd.building_id = b.building_id
        WHERE district_id = 4
"""
print(query)

        SELECT DISTINCT(i.building_id) AS b_id,
        b.*,
        bd.damage_grade
        FROM id_map AS i
        JOIN building_structure AS b
        ON i.building_id = b.building_id
        JOIN building_damage AS bd
        ON bd.building_id = b.building_id
        WHERE district_id = 4

In [19]:
import pandas as pd
df = pd.read_sql(query, engine, index_col="b_id")
df.head()

,building_id,count_floors_pre_eq,count_floors_post_eq,age_building,plinth_area_sq_ft,height_ft_pre_eq,height_ft_post_eq,land_surface_condition,foundation_type,roof_type,ground_floor_type,other_floor_type,position,plan_configuration,condition_post_eq,superstructure,damage_grade
b_id,,,,,,,,,,,,,,,,,
164000,164000,1,0,40,336,6,0,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,Not applicable,Not attached,Rectangular,Damaged-Rubble unclear,"Stone, mud mortar",Grade 5
164001,164001,2,2,12,420,13,13,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Damaged-Used in risk,"Stone, mud mortar",Grade 3
164002,164002,3,3,20,560,18,18,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Damaged-Repaired and used,"Stone, mud mortar",Grade 2
164003,164003,2,2,15,390,12,12,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Rectangular,Damaged-Used in risk,"Stone, mud mortar",Grade 4
164004,164004,2,2,15,290,13,13,Flat,Mud mortar-Stone/Brick,Bamboo/Timber-Light roof,Mud,TImber/Bamboo-Mud,Not attached,Square,Damaged-Not used,"Stone, mud mortar",Grade 4

Aggregation functions take a collection of values as inputs and return one value as the output. The table below gives the frequently used built-in aggregation functions:

| Aggregation Function | Definition                        |
| -------------------- | --------------------------------- |
| `MIN`                  | Return the minimum value          |
| `MAX`                  | Return the largest value          |
| `SUM`                  | Return the sum of values          |
| `AVG`                  | Return the average of values      |
| `COUNT`                | Return the number of observations |

Use the `COUNT` function to find the number of observations in the `id_map` table that come from Ramechhap (district `2`):

Aggregation functions are frequently used with a `GROUP BY` clause to perform the aggregation on groups of data. For example, the query below returns the count of observations in each District:

 `DISTINCT` is a keyword to select unique records in a query result. For example, if we want to know the unique values in the `district_id` column:

`DISTINCT` and `COUNT` can be used in combination to count the number of distinct records. For example, if we want to know the number of unique values in the `district_id` column:

Joins link data from two or more tables together by using a column that is common between the two tables. The basic syntax for a join is below, where `table1` and `table2` refer to the two tables being joined, `column1` and `column2` refer to columns to be returned from both tables, and `ID` refers to the common column in the two tables. 

```sql
SELECT table1.column1,
       table2.column2
FROM table_1
JOIN table2 ON table1.id = table1.id
```

We'll explore the concept of joins by first identifying a single household that we'd like to pull in building information for. For example, let's say we want to see the corresponding `foundation_type` for the first home in Ramechhap (District 1). We'll start by looking at this single record in the `id_map` table.

This household has `building_id` equal to 23. Let's look at the `foundation_type` for this building, by filtering the `building_structure` table to find this building.

To join the two tables and limit the results to `building_id = 23`:

# <font size="+3"><strong>Databases: PyMongo</strong></font>

# Working with PyMongo

We're going to be working with the `"lagos"` collection in the `"air-quality"` database. Before we can do anything else, pprint (a module that lets us see the data in an understandable way), and PyMongo (a library for working with MongoDB databases).

In [13]:
from pprint import PrettyPrinter

import pandas as pd
from pymongo import MongoClient

## Servers and Clients

Next, we need to connect to a server. A database **server** is where the database resides; it can be accessed using a **client**. Without a client, a database is just a collection of information that we can't work with, because we have no way in. We're going to be learning more about a database called MongoDB, and we'll use `PrettyPrinter` to make the information it generates easier to understand. Here's how the connection works:

In [14]:
client = MongoClient("mongodb://datalab:datalab@localhost:27017")

## Semi-structured Data

Databases are designed to work with either structured data or semi-structured data. In this part of the course, we're going to be working with databases that contain **semi-structured data**. Data is semi-structured when it has some kind of organizing logic, but that logic can't be displayed using rows and columns. Your email account contains semi-structured data if it’s divided into sections like *Inbox*, *Sent*, and *Trash*. If you’ve ever seen tweets from Twitter grouped by hashtag, that’s semi-structured data too. Semi-structured data is also used in sensor readings, which is what we'll be working with here.

## Exploring a Database

So, now that we're connected to a server, let's take a look at what's there. Working our way down the specificity scale, the first thing we need to do is figure out which databases are on this server. To see which databases on the server, we'll use the [`list_databases`](https://pymongo.readthedocs.io/en/stable/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient.list_databases) method, like this:

In [31]:
database = client.list_databases().to_list()
database

[{'name': 'admin', 'sizeOnDisk': 102400, 'empty': False},
 {'name': 'air-quality', 'sizeOnDisk': 6574080, 'empty': False},
 {'name': 'config', 'sizeOnDisk': 110592, 'empty': False},
 {'name': 'local', 'sizeOnDisk': 73728, 'empty': False},
 {'name': 'wqu-abtest', 'sizeOnDisk': 528384, 'empty': False}]

In [32]:
for i in database:
    print(i)

{'name': 'admin', 'sizeOnDisk': 102400, 'empty': False}
{'name': 'air-quality', 'sizeOnDisk': 6574080, 'empty': False}
{'name': 'config', 'sizeOnDisk': 110592, 'empty': False}
{'name': 'local', 'sizeOnDisk': 73728, 'empty': False}
{'name': 'wqu-abtest', 'sizeOnDisk': 528384, 'empty': False}

In [33]:
next(iter(client.list_databases()))

{'name': 'admin', 'sizeOnDisk': 102400, 'empty': False}

It looks like this server contains four databases: `"admin"`, `"air-quality"`, `"config"`, and `"local"`. We're only interested in `"air-quality"`, so let's connect to that one:

In [34]:
db = client['air-quality']

In MongoDB, a **database** is a container for **collections**. Each database gets its own set of files, and a single MongoDB **server** typically has multiple databases.

## Collections

Let's use a `for` loop to take a look at the collections in the "`air-quality"` database:

In [36]:
lagos = db["lagos"]

In [37]:
lagos.count_documents({})

166496

As you can see, there are three actual collections here: `"nairobi"`, `"lagos"`, and `"dar-es-salaam"`. Since we're only interested in the `"lagos"` collection, let's get it on its own like this:

A MongoDB **document** is an individual record of data in a **collection**, and is the basic unit of analysis in MongoDB. Documents come with **metadata** that helps us understand what the document is; we'll get back to that in a minute. In the meantime, let's use the [`count_documents`](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.count_documents) method to see how many documents the `"lagos"` collection contains:

In [38]:
nairobi = db["nairobi"]
nairobi.count_documents({})

202212

### Retrieving Data

Now that we know how many documents the `"lagos"` collection contains, let's take a closer look at what's there. The first thing you'll notice is that the output starts out with a curly bracket (`{`), and ends with a curly bracket (`}`). That tells us that this information is a **dictionary**.  To access documents in the collection, we'll use two methods: [`find`](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.find) and [`find_one`](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.find_one). As you might expect, `find` will retrieve all the documents, and `find_one` will bring back only the first document. For now, let's stick to `find_one`; we'll come back to `find` later.

Just like everywhere else, we'll need to assign a variable name to whatever comes back, so let's call this one `result`.

In [39]:
pp = PrettyPrinter(indent=2)

In [41]:
result = lagos.find_one({})
result

{'timestamp': datetime.datetime(2018, 1, 7, 7, 7, 3, 39000),
 'metadata': {'lat': 6.501,
  'lon': 3.367,
  'measurement': 'P1',
  'sensor_id': 6,
  'sensor_type': 'PPD42NS',
  'site': 4},
 '_id': ObjectId('6acba61c33e1a57a65fe586e'),
 'P1': 20.47}

In [42]:
pp.pprint(result)

{ 'P1': 20.47,
  '_id': ObjectId('6acba61c33e1a57a65fe586e'),
  'metadata': { 'lat': 6.501,
                'lon': 3.367,
                'measurement': 'P1',
                'sensor_id': 6,
                'sensor_type': 'PPD42NS',
                'site': 4},
  'timestamp': datetime.datetime(2018, 1, 7, 7, 7, 3, 39000)}

### Key-Value Pairs

There's a lot going on here! Let's work from the bottom up, starting with this: 

```python
{
    'temperature': 27.0,
    'timestamp': datetime.datetime(2017, 9, 6, 13, 18, 10, 120000)
}
```


The actual data is labeled `temperature` and `timestamp`, and if seeing it presented this way seems familiar, that's because what you're seeing at the bottom are two **key-value pairs**.  In PyMongo, `"_id"` is always the **primary key**. Primary keys are the column(s) which contain values that uniquely identify each row in a table; we'll talk about that more in a minute.

### Metadata

Next, we have this: 

```python
'metadata': { 'lat': 6.602,
              'lon': 3.351,
              'measurement': 'temperature',
              'sensor_id': 9,
              'sensor_type': 'DHT11',
              'site': 2}
```
                
This is the document's **metadata**. Metadata is data about the data. If you’re working with a database, its data is the information it contains, and its metadata describes what that information is. In MongoDB, each document often has metadata of its own. If we go back to the example of your email account, each message in your *Sent* folder includes both the message itself and information about when you sent it and who you sent it to; the message is data, and the other information is metadata.

The metadata we see in this block of code tells us what the key-value pairs from the last code block mean, and where the information stored there comes from. There's location data, a line telling us what about the format of the key-value pairs, some information about the equipment used to gather the data, and where the data came from.

### Identifiers

Finally, at the top, we have this:

```python
{ 
    '_id': ObjectId('6126f1780e45360640bf240a')
}
```

This is the document's unique identifier, which is similar to the index label for each row in a pandas DataFrame.

## Analyzing Data

Now that we've seen what a document looks like in this collection, let's start working with what we've got. Since our metadata includes information about each sensor's `"site"`, we might be curious to know how many sites are in the `"lagos"` collection. To do that, we'll use the [`distinct`](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.distinct) method, like this:

In [43]:
lagos.distinct('metadata.site')

[4, 3]

Notice that in order to grab the `"site"` number, we needed to include the `"metadata"` tag. 

This tells us that there are 2 sensor sites in Lagos: one labeled `3` and the other labeled `4`.

Let's go further. We know that there are two sensor sites in Lagos, but we don't know how many documents are associated with each site. To find that out, we'll use the [`count_documents`](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.count_documents) method for each site.

In [45]:
lagos.count_documents({"metadata.site": 3})

140586

In [46]:
lagos.count_documents({"metadata.site": 4})

25910

Now that we know how many *documents* are associated with each site, let's keep drilling down and find the number of *readings* for each site. We'll do this with the [`aggregate`](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.aggregate) method.

Before we run it, let's take a look at some of what's happening in the code here. First, you'll notice that there are several dollar signs (`$`) in the list. This is telling the collection that we want to create something new. Here, we're saying that we want there to be a new `group`, and that the new group needs to be updated with data from `metadata.site`, and then updated again with data from `count`.

There's also a new field: `"_id"`. In PyMongo, `"_id"` is always the **primary key**. Primary keys are the fields which contain values that uniquely identify each row in a table. 

Let's run the code and see what happens:

In [50]:
result = lagos.aggregate(
    [{"$group":
     {"_id": "$metadata.site",
      "count": {"$count": {}}}
     }]
)

pp.pprint(result.to_list())

[{'_id': 4, 'count': 25910}, {'_id': 3, 'count': 140586}]

With that information in mind, we might want to know what those readings actually are. Since we're really interested in measures of air quality, let's take a look at the `P2` values in the `"lagos"` collection. `P2` measures the amount of particulate matter in the air, which in this case is something called PM 2.5. If we wanted to get all the documents in a collection, we could, but that would result in an unmanageably large number of records clogging up the memory on our machines. Instead, let's use the [`find`](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.find) method and use `limit` to make sure we only get back the first 3.

In [52]:
result = lagos.find({"metadata.measurement": "P2"}).limit(10)
pp.pprint(result.to_list())

[ { 'P2': 14.42,
    '_id': ObjectId('6acba61c33e1a57a65fe586f'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P2',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 7, 3, 39000)},
  { 'P2': 19.66,
    '_id': ObjectId('6acba61c33e1a57a65fe5873'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P2',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 11, 23, 870000)},
  { 'P2': 24.79,
    '_id': ObjectId('6acba61c33e1a57a65fe5877'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P2',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 21, 53, 981000)},
  { 'P2': 49.43,
    '_id': ObjectId('6acba61c33e1a57a65fe587b'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P2',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 29, 36, 622000)},
  { 'P2': 49.59,
    '_id': ObjectId('6acba61c33e1a57a65fe587f'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P2',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 35, 36, 476000)},
  { 'P2': 10.53,
    '_id': ObjectId('6acba61c33e1a57a65fe5883'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P2',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 42, 47, 439000)},
  { 'P2': 55.17,
    '_id': ObjectId('6acba61c33e1a57a65fe5887'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P2',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 1, 8, 885000)},
  { 'P2': 85.96,
    '_id': ObjectId('6acba61c33e1a57a65fe588b'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P2',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 15, 32, 615000)},
  { 'P2': 80.71,
    '_id': ObjectId('6acba61c33e1a57a65fe588f'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P2',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 28, 19, 405000)},
  { 'P2': 80.71,
    '_id': ObjectId('6acba61c33e1a57a65fe5893'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P2',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 31, 24, 982000)}]

In [53]:
result = lagos.find({"metadata.measurement": "P1"}).limit(10)
pp.pprint(result.to_list())

[ { 'P1': 20.47,
    '_id': ObjectId('6acba61c33e1a57a65fe586e'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P1',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 7, 3, 39000)},
  { 'P1': 30.08,
    '_id': ObjectId('6acba61c33e1a57a65fe5872'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P1',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 11, 23, 870000)},
  { 'P1': 22.33,
    '_id': ObjectId('6acba61c33e1a57a65fe5876'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P1',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 21, 53, 981000)},
  { 'P1': 52.19,
    '_id': ObjectId('6acba61c33e1a57a65fe587a'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P1',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 29, 36, 622000)},
  { 'P1': 55.6,
    '_id': ObjectId('6acba61c33e1a57a65fe587e'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P1',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 35, 36, 476000)},
  { 'P1': 19.71,
    '_id': ObjectId('6acba61c33e1a57a65fe5882'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P1',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 42, 47, 439000)},
  { 'P1': 84.0,
    '_id': ObjectId('6acba61c33e1a57a65fe5886'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P1',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 1, 8, 885000)},
  { 'P1': 117.29,
    '_id': ObjectId('6acba61c33e1a57a65fe588a'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P1',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 15, 32, 615000)},
  { 'P1': 96.95,
    '_id': ObjectId('6acba61c33e1a57a65fe588e'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P1',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 28, 19, 405000)},
  { 'P1': 96.95,
    '_id': ObjectId('6acba61c33e1a57a65fe5892'),
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'P1',
                  'sensor_id': 6,
                  'sensor_type': 'PPD42NS',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 31, 24, 982000)}]

In [55]:
result = lagos.find({"metadata.measurement": "humidity"}).limit(10)
pp.pprint(result.to_list())

[ { '_id': ObjectId('6acba61c33e1a57a65fe5870'),
    'humidity': nan,
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'humidity',
                  'sensor_id': 10,
                  'sensor_type': 'DHT11',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 7, 3, 88000)},
  { '_id': ObjectId('6acba61c33e1a57a65fe5874'),
    'humidity': nan,
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'humidity',
                  'sensor_id': 10,
                  'sensor_type': 'DHT11',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 11, 23, 919000)},
  { '_id': ObjectId('6acba61c33e1a57a65fe5878'),
    'humidity': nan,
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'humidity',
                  'sensor_id': 10,
                  'sensor_type': 'DHT11',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 21, 54, 32000)},
  { '_id': ObjectId('6acba61c33e1a57a65fe587c'),
    'humidity': nan,
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'humidity',
                  'sensor_id': 10,
                  'sensor_type': 'DHT11',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 29, 36, 673000)},
  { '_id': ObjectId('6acba61c33e1a57a65fe5880'),
    'humidity': nan,
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'humidity',
                  'sensor_id': 10,
                  'sensor_type': 'DHT11',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 35, 36, 527000)},
  { '_id': ObjectId('6acba61c33e1a57a65fe5884'),
    'humidity': nan,
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'humidity',
                  'sensor_id': 10,
                  'sensor_type': 'DHT11',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 7, 42, 47, 492000)},
  { '_id': ObjectId('6acba61c33e1a57a65fe5888'),
    'humidity': nan,
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'humidity',
                  'sensor_id': 10,
                  'sensor_type': 'DHT11',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 1, 8, 934000)},
  { '_id': ObjectId('6acba61c33e1a57a65fe588c'),
    'humidity': nan,
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'humidity',
                  'sensor_id': 10,
                  'sensor_type': 'DHT11',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 15, 32, 665000)},
  { '_id': ObjectId('6acba61c33e1a57a65fe5890'),
    'humidity': nan,
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'humidity',
                  'sensor_id': 10,
                  'sensor_type': 'DHT11',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 28, 19, 454000)},
  { '_id': ObjectId('6acba61c33e1a57a65fe5894'),
    'humidity': nan,
    'metadata': { 'lat': 6.501,
                  'lon': 3.367,
                  'measurement': 'humidity',
                  'sensor_id': 10,
                  'sensor_type': 'DHT11',
                  'site': 4},
    'timestamp': datetime.datetime(2018, 1, 7, 8, 31, 25, 67000)}]

So far, we've been dealing with relatively small subsets of the data in our collections, but what if we need to work with something bigger? Let's start by using `distinct` to remind ourselves of the kinds of data we have at our disposal.

In [54]:
lagos.distinct("metadata.measurement")

['P1', 'humidity', 'temperature', 'P2']

There are also comparison query operators that can be helpful for filtering the data. In total, we have 

- `$gt`:  greater than (>)
- `$lt`:  less than (<) 
- `$gte`: greater than equal to (>=)
- `$lte`: less than equal to (<= )

Let's use the `timestamp` to see how we can use these operators to select different documents:

In [60]:
import datetime

result = nairobi.find(
    {"timestamp":
    {"$gt": datetime.datetime(2018, 7, 1)}
    }
).limit(10)

pp.pprint(result.to_list())

[ { 'P1': 39.67,
    '_id': ObjectId('6acba5ff33e1a57a65fb428a'),
    'metadata': { 'lat': -1.3,
                  'lon': 36.785,
                  'measurement': 'P1',
                  'sensor_id': 57,
                  'sensor_type': 'SDS011',
                  'site': 29},
    'timestamp': datetime.datetime(2018, 9, 1, 0, 0, 2, 472000)},
  { 'P1': 39.13,
    '_id': ObjectId('6acba5ff33e1a57a65fb428e'),
    'metadata': { 'lat': -1.3,
                  'lon': 36.785,
                  'measurement': 'P1',
                  'sensor_id': 57,
                  'sensor_type': 'SDS011',
                  'site': 29},
    'timestamp': datetime.datetime(2018, 9, 1, 0, 5, 3, 941000)},
  { 'P1': 30.07,
    '_id': ObjectId('6acba5ff33e1a57a65fb4292'),
    'metadata': { 'lat': -1.3,
                  'lon': 36.785,
                  'measurement': 'P1',
                  'sensor_id': 57,
                  'sensor_type': 'SDS011',
                  'site': 29},
    'timestamp': datetime.datetime(2018, 9, 1, 0, 10, 4, 374000)},
  { 'P1': 19.1,
    '_id': ObjectId('6acba5ff33e1a57a65fb4296'),
    'metadata': { 'lat': -1.3,
                  'lon': 36.785,
                  'measurement': 'P1',
                  'sensor_id': 57,
                  'sensor_type': 'SDS011',
                  'site': 29},
    'timestamp': datetime.datetime(2018, 9, 1, 0, 15, 4, 245000)},
  { 'P1': 26.43,
    '_id': ObjectId('6acba5ff33e1a57a65fb429a'),
    'metadata': { 'lat': -1.3,
                  'lon': 36.785,
                  'measurement': 'P1',
                  'sensor_id': 57,
                  'sensor_type': 'SDS011',
                  'site': 29},
    'timestamp': datetime.datetime(2018, 9, 1, 0, 20, 4, 869000)},
  { 'P1': 22.53,
    '_id': ObjectId('6acba5ff33e1a57a65fb429e'),
    'metadata': { 'lat': -1.3,
                  'lon': 36.785,
                  'measurement': 'P1',
                  'sensor_id': 57,
                  'sensor_type': 'SDS011',
                  'site': 29},
    'timestamp': datetime.datetime(2018, 9, 1, 0, 25, 4, 659000)},
  { 'P1': 28.6,
    '_id': ObjectId('6acba5ff33e1a57a65fb42a2'),
    'metadata': { 'lat': -1.3,
                  'lon': 36.785,
                  'measurement': 'P1',
                  'sensor_id': 57,
                  'sensor_type': 'SDS011',
                  'site': 29},
    'timestamp': datetime.datetime(2018, 9, 1, 0, 30, 5, 406000)},
  { 'P1': 26.47,
    '_id': ObjectId('6acba5ff33e1a57a65fb42a6'),
    'metadata': { 'lat': -1.3,
                  'lon': 36.785,
                  'measurement': 'P1',
                  'sensor_id': 57,
                  'sensor_type': 'SDS011',
                  'site': 29},
    'timestamp': datetime.datetime(2018, 9, 1, 0, 35, 4, 259000)},
  { 'P1': 15.77,
    '_id': ObjectId('6acba5ff33e1a57a65fb42aa'),
    'metadata': { 'lat': -1.3,
                  'lon': 36.785,
                  'measurement': 'P1',
                  'sensor_id': 57,
                  'sensor_type': 'SDS011',
                  'site': 29},
    'timestamp': datetime.datetime(2018, 9, 1, 0, 40, 4, 219000)},
  { 'P1': 16.03,
    '_id': ObjectId('6acba5ff33e1a57a65fb42ae'),
    'metadata': { 'lat': -1.3,
                  'lon': 36.785,
                  'measurement': 'P1',
                  'sensor_id': 57,
                  'sensor_type': 'SDS011',
                  'site': 29},
    'timestamp': datetime.datetime(2018, 9, 1, 0, 45, 4, 42000)}]

We can also update documents by passing some filter and new values using `update_one` to update one record or `update_many` to update many records. Let's look at an example. Before updating, we have this record showing like this:

Now we are updating the sensor type from `"SDS011"` to `"SDS"`, we first select all records with sensor type equal to `"SDS011"`, then set the new value to `"SDS"`:

Since we're looking for *big* numbers, we need to figure out which one of those dimensions has the largest number of measurements by **aggregating** the data in each document. Since we already know that `site 3` has significantly more documents than `site 2`, let's start looking at `site 3`. We can use the `$match` syntax to only select `site 3` data. The code to do that looks like this:

After aggregation, there is another useful operator called `$project`, which allows you to specify which fields to display by adding new fields or deleting fields. Using the Nairobi data from site 29, we can first count each sensor type:<span style='color: transparent; font-size:1%'>WQU WorldQuant University Applied Data Science Lab QQQQ</span>

We can see there are two sensor types and the corresponding counts. If we only want to display what are the types but do not care about the counts, we can suppress the `count` filed by setting it at 0 in `$project`:

The `$project` syntax is also useful for deleting the intermediate fields that we used to generate our final fields but no longer need. In the following example, let's calculate the date difference for each sensor type. We'll first use the aggregation method to get the start date and last date.

Then we can calculate the date difference using `$dateDiff`, which gets the date difference through specifying the start date, end date and unit for timestamp data. We can see from the results above that the dates, are very close to each other. The only differences are in the minutes, so we can specify the unit as minute to show the difference. Since we don't need the start date and end dates, we can define a `"dateDiff"` field inside `$project`, so that it will be shown in the final display:

We can do more with the date data using `$dateTrunc`, which truncates datetime data. We need to specify the datetime data, which can be a `Date`, a `Timestamp`, or an `ObjectID`. Then we need to specify the `unit` (year, month, day, hour, minute, second) and `binSize` (numerical variable defining the size of the truncation). Let's check the example below, where we group data by the month using `$dateTrunc` and then count how many observations there are for each month.