In [2]:
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/

In [3]:
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!pip install -q kaggle

In [5]:
!kaggle datasets files shengkunwang/housets-dataset

Next Page Token = CfDJ8L9-_gcGHthJtufiBgcc1oaYTn6gLjg6wPPXqK0PP7Mqo6MulZSW4AOTM59dfD0wSQyDBXbBY-6a3eUjzN9C2uzBcLxu89GVmReMi72vmASsdUllimqYD90xt54nuodrqJWMUgJMesA5yux6CWXIdmOp2LkOqr6ay-cTVwlppeHwCqk8E9Svwn8I2wKqZW7upvMrI5ftRcQ
name                                                                  size  creationDate
---------------------------------------------------------------  ---------  --------------------------
HouseTS.csv                                                      284616105  2026-02-05 22:18:33.928000
Housets_Image/Housets_Final/Atlanta/30002/30002_2013.png            382923  2026-02-05 22:21:15.840000
Housets_Image/Housets_Final/Atlanta/30002/30002_2015.png            365211  2026-02-05 22:21:15.879000
Housets_Image/Housets_Final/Atlanta/30002/30002_2017.png            377068  2026-02-05 22:21:15.869000
Housets_Image/Housets_Final/Atlanta/30002/30002_2019.png            380397  2026-02-05 22:21:15.846000
Housets_Image/Housets_Final/Atlanta/30002/30002_2021.png            392973  2026-02-05 22:21:15.863000
Housets_Image/Housets_Final/Atlanta/30002/30002_2023.png            382790  2026-02-05 22:21:15.834000
Housets_Image/Housets_Final/Atlanta/30002/GLM-4.5V-AWQ.json           1067  2026-02-05 22:21:15.834000
Housets_Image/Housets_Final/Atlanta/30002/final_annotation.json       1366  2026-02-05 22:21:15.834000
Housets_Image/Housets_Final/Atlanta/30002/gemini-2.5-pro.json         1562  2026-02-05 22:21:15.834000
Housets_Image/Housets_Final/Atlanta/30002/gpt-5-mini.json             1625  2026-02-05 22:21:15.824000
Housets_Image/Housets_Final/Atlanta/30002/gpt-5.1.json                1761  2026-02-05 22:21:15.829000
Housets_Image/Housets_Final/Atlanta/30002/judge_gpt-5.2.json          1919  2026-02-05 22:21:15.840000
Housets_Image/Housets_Final/Atlanta/30004/30004_2013.png            382080  2026-02-05 22:21:14.151000
Housets_Image/Housets_Final/Atlanta/30004/30004_2015.png            377260  2026-02-05 22:21:14.186000
Housets_Image/Housets_Final/Atlanta/30004/30004_2017.png            385473  2026-02-05 22:21:14.144000
Housets_Image/Housets_Final/Atlanta/30004/30004_2019.png            407204  2026-02-05 22:21:14.130000
Housets_Image/Housets_Final/Atlanta/30004/30004_2022.png            417393  2026-02-05 22:21:14.158000
Housets_Image/Housets_Final/Atlanta/30004/30004_2023.png            404965  2026-02-05 22:21:14.144000
Housets_Image/Housets_Final/Atlanta/30004/GLM-4.5V-AWQ.json           1536  2026-02-05 22:21:14.136000

In [6]:
!kaggle datasets download -d shengkunwang/housets-dataset -f HouseTS.csv

Dataset URL: https://www.kaggle.com/datasets/shengkunwang/housets-dataset
License(s): CC-BY-NC-SA-4.0
Downloading HouseTS.csv to /content
100% 271M/271M [00:18<00:00, 15.1MB/s]

In [7]:
import pandas as pd
pd.set_option('display.max_columns', None) # Show all columns
pd.set_option('display.max_rows', None) # Show all rows

In [8]:
df = pd.read_csv("/content/HouseTS.csv") # C:\Users\HP\Desktop\3mtt\Build-Deploy-Regression-Time-Series-ML-FastAPI-MLFlow-Docker-CI-CD-AWS\data\raw\HouseTS.csv
df.head()

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Alpharetta
1,2012-04-30,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,0.946642,0.090909,0.034483,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,Atlanta-Sandy Springs-Alpharetta
2,2012-05-31,125500.0,217450.0,63.913043,119.919216,24.0,40.0,63.0,60.0,144.5,0.955624,0.208333,0.100000,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202681.309539,Atlanta-Sandy Springs-Alpharetta
3,2012-06-30,153000.0,189900.0,81.598080,105.617353,34.0,46.0,50.0,57.0,126.0,0.970608,0.176471,0.108696,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202998.603897,Atlanta-Sandy Springs-Alpharetta
4,2012-07-31,165500.0,154000.0,81.598080,83.921175,39.0,49.0,42.0,50.0,80.0,0.982105,0.256410,0.102041,ATL,30002,2012,12.0,2.0,3.0,1.0,60.0,45.0,57.0,4.0,6.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,203781.903446,Atlanta-Sandy Springs-Alpharetta

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 884092 entries, 0 to 884091
Data columns (total 39 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date                          884092 non-null  object
 1   median_sale_price             884092 non-null  float64
 2   median_list_price             884092 non-null  float64
 3   median_ppsf                   884092 non-null  float64
 4   median_list_ppsf              884092 non-null  float64
 5   homes_sold                    884092 non-null  float64
 6   pending_sales                 884092 non-null  float64
 7   new_listings                  884092 non-null  float64
 8   inventory                     884092 non-null  float64
 9   median_dom                    884092 non-null  float64
 10  avg_sale_to_list              884092 non-null  float64
 11  sold_above_list               884092 non-null  float64
 12  off_market_in_two_weeks       884092 non-null  float64
 13  city                          884092 non-null  object
 14  zipcode                       884092 non-null  int64
 15  year                          884092 non-null  int64
 16  bank                          884092 non-null  float64
 17  bus                           884092 non-null  float64
 18  hospital                      884092 non-null  float64
 19  mall                          884092 non-null  float64
 20  park                          884092 non-null  float64
 21  restaurant                    884092 non-null  float64
 22  school                        884092 non-null  float64
 23  station                       884092 non-null  float64
 24  supermarket                   884092 non-null  float64
 25  Total Population              884092 non-null  float64
 26  Median Age                    884092 non-null  float64
 27  Per Capita Income             884092 non-null  float64
 28  Total Families Below Poverty  884092 non-null  float64
 29  Total Housing Units           884092 non-null  float64
 30  Median Rent                   884092 non-null  float64
 31  Median Home Value             884092 non-null  float64
 32  Total Labor Force             884092 non-null  float64
 33  Unemployed Population         884092 non-null  float64
 34  Total School Age Population   884092 non-null  float64
 35  Total School Enrollment       884092 non-null  float64
 36  Median Commute Time           884092 non-null  float64
 37  price                         884092 non-null  float64
 38  city_full                     884092 non-null  object
dtypes: float64(34), int64(2), object(3)
memory usage: 263.1+ MB

In [10]:
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 884092 entries, 0 to 884091
Data columns (total 39 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date                          884092 non-null  datetime64[ns]
 1   median_sale_price             884092 non-null  float64
 2   median_list_price             884092 non-null  float64
 3   median_ppsf                   884092 non-null  float64
 4   median_list_ppsf              884092 non-null  float64
 5   homes_sold                    884092 non-null  float64
 6   pending_sales                 884092 non-null  float64
 7   new_listings                  884092 non-null  float64
 8   inventory                     884092 non-null  float64
 9   median_dom                    884092 non-null  float64
 10  avg_sale_to_list              884092 non-null  float64
 11  sold_above_list               884092 non-null  float64
 12  off_market_in_two_weeks       884092 non-null  float64
 13  city                          884092 non-null  object
 14  zipcode                       884092 non-null  int64
 15  year                          884092 non-null  int64
 16  bank                          884092 non-null  float64
 17  bus                           884092 non-null  float64
 18  hospital                      884092 non-null  float64
 19  mall                          884092 non-null  float64
 20  park                          884092 non-null  float64
 21  restaurant                    884092 non-null  float64
 22  school                        884092 non-null  float64
 23  station                       884092 non-null  float64
 24  supermarket                   884092 non-null  float64
 25  Total Population              884092 non-null  float64
 26  Median Age                    884092 non-null  float64
 27  Per Capita Income             884092 non-null  float64
 28  Total Families Below Poverty  884092 non-null  float64
 29  Total Housing Units           884092 non-null  float64
 30  Median Rent                   884092 non-null  float64
 31  Median Home Value             884092 non-null  float64
 32  Total Labor Force             884092 non-null  float64
 33  Unemployed Population         884092 non-null  float64
 34  Total School Age Population   884092 non-null  float64
 35  Total School Enrollment       884092 non-null  float64
 36  Median Commute Time           884092 non-null  float64
 37  price                         884092 non-null  float64
 38  city_full                     884092 non-null  object
dtypes: datetime64[ns](1), float64(34), int64(2), object(2)
memory usage: 263.1+ MB

In [11]:
df.date.dt.year.value_counts()

date
2013    74712
2014    74712
2015    74712
2016    74712
2020    74712
2017    74712
2018    74712
2019    74712
2022    74712
2021    74712
2023    74712
2012    62260
Name: count, dtype: int64

In [12]:
new_df = df.sort_values("date")
new_df.head()

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Alpharetta
640562,2012-03-31,200000.0,7500.0,104.931794,79.265873,1.0,1.0,1.0,2.0,290.0,0.909091,0.000000,0.000000,PGH,15469,2012,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,2441.0,41.8,20241.0,2385.0,1108.0,641.0,94600.0,1171.0,52.0,2376.0,2376.0,1018.0,105863.681174,Pittsburgh
640420,2012-03-31,75750.0,92400.0,165.898618,63.412698,2.0,2.0,4.0,13.0,193.0,0.986815,0.000000,0.000000,PGH,15468,2012,0.0,0.0,0.0,0.0,1.0,0.0,5.0,0.0,0.0,2171.0,47.8,18740.0,2094.0,1252.0,627.0,62800.0,894.0,30.0,2106.0,2106.0,807.0,60152.096646,Pittsburgh
640278,2012-03-31,79900.0,79900.0,0.696203,0.000000,1.0,1.0,1.0,1.0,46.0,1.000000,0.000000,0.000000,PGH,15466,2012,1.0,0.0,0.0,0.0,0.0,2.0,8.0,0.0,0.0,425.0,46.8,23067.0,425.0,208.0,534.0,66200.0,216.0,7.0,414.0,414.0,208.0,44042.242632,Pittsburgh
640136,2012-03-31,196000.0,198000.0,122.807018,124.060150,1.0,1.0,1.0,1.0,49.0,0.989899,0.000000,0.000000,PGH,15464,2012,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,1515.0,45.1,18623.0,1508.0,692.0,484.0,79300.0,711.0,61.0,1489.0,1489.0,641.0,126572.277873,Pittsburgh

In [13]:
train_df = df[new_df['date'] < "2020-01-01"]
test_df = new_df[(new_df['date'] >= "2020-01-01") & (new_df['date'] < "2021-12-31")]
eval_df = df[df['date'] > "2021-12-31"]

/tmp/ipykernel_18128/2591873398.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  train_df = df[new_df['date'] < "2020-01-01"]

In [14]:
print(train_df.shape)
print(test_df.shape)
print(eval_df.shape)

(585244, 39)
(143198, 39)
(149424, 39)

In [15]:
train_df.head()

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,Atlanta-Sandy Springs-Alpharetta
1,2012-04-30,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,0.946642,0.090909,0.034483,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,Atlanta-Sandy Springs-Alpharetta
2,2012-05-31,125500.0,217450.0,63.913043,119.919216,24.0,40.0,63.0,60.0,144.5,0.955624,0.208333,0.100000,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202681.309539,Atlanta-Sandy Springs-Alpharetta
3,2012-06-30,153000.0,189900.0,81.598080,105.617353,34.0,46.0,50.0,57.0,126.0,0.970608,0.176471,0.108696,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202998.603897,Atlanta-Sandy Springs-Alpharetta
4,2012-07-31,165500.0,154000.0,81.598080,83.921175,39.0,49.0,42.0,50.0,80.0,0.982105,0.256410,0.102041,ATL,30002,2012,12.0,2.0,3.0,1.0,60.0,45.0,57.0,4.0,6.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,203781.903446,Atlanta-Sandy Springs-Alpharetta

In [16]:
test_df.head()

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
137976,2020-01-31,184000.0,168450.0,123.333333,109.899800,35.0,30.0,34.0,37.0,50.0,0.954732,0.171429,0.300000,CHI,60482,2020,3.0,0.0,2.0,0.0,68.0,30.0,60.0,5.0,14.0,10849.0,42.1,27037.0,10795.0,4598.0,964.0,169000.0,5690.0,414.0,10573.0,10573.0,5089.0,1.648397e+05,Chicago-Naperville-Elgin
157714,2020-01-31,140000.0,139000.0,94.691957,111.311054,61.0,81.0,83.0,54.0,10.0,0.963039,0.098361,0.469136,CIN,41071,2020,35.0,5.0,4.0,3.0,139.0,259.0,86.0,1.0,8.0,20624.0,36.6,30324.0,19423.0,10164.0,802.0,132400.0,10479.0,552.0,19809.0,19809.0,9383.0,1.321643e+05,Cincinnati
523364,2020-01-31,1040000.0,1600000.0,1386.111111,1801.309410,134.0,151.0,210.0,563.0,188.0,0.971567,0.037313,0.006623,NY,10023,2020,344.0,11.0,26.0,8.0,404.0,2054.0,324.0,114.0,172.0,62541.0,43.3,126937.0,60995.0,41353.0,2346.0,1218900.0,37308.0,1440.0,60206.0,60206.0,31554.0,1.494755e+06,New York-Newark-Jersey City
71946,2020-01-31,459000.0,550000.0,233.574442,243.803182,21.0,16.0,15.0,34.0,97.0,0.963443,0.095238,0.062500,BOS,2738,2020,0.0,0.0,1.0,0.0,14.0,0.0,10.0,0.0,0.0,5132.0,50.2,53105.0,4987.0,2481.0,1279.0,483500.0,2400.0,104.0,5036.0,5036.0,1957.0,4.882322e+05,Boston-Cambridge-Newton
123492,2020-01-31,203000.0,219900.0,183.644102,191.074971,14.0,18.0,16.0,15.0,42.0,0.961928,0.285714,0.388889,CHI,60163,2020,13.0,0.0,1.0,4.0,88.0,26.0,78.0,4.0,9.0,5103.0,38.8,29393.0,5093.0,1848.0,956.0,178700.0,2682.0,197.0,4934.0,4934.0,2425.0,1.944681e+05,Chicago-Naperville-Elgin

In [17]:
eval_df.head()

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
118,2022-01-31,575500.0,459900.0,211.746522,246.811160,45.0,39.0,35.0,21.0,17.0,1.005392,0.400000,0.538462,ATL,30002,2022,14.0,1.0,3.0,1.0,70.0,70.0,62.0,4.0,14.0,6025.0,41.2,54743.0,6007.0,3149.0,933.0,432400.0,3417.0,82.0,5713.0,5713.0,2728.0,452676.155824,Atlanta-Sandy Springs-Alpharetta
119,2022-02-28,574146.5,470000.0,215.718552,248.941469,48.0,33.0,36.0,18.0,16.0,1.010408,0.500000,0.696970,ATL,30002,2022,14.0,1.0,3.0,1.0,70.0,70.0,62.0,4.0,14.0,6025.0,41.2,54743.0,6007.0,3149.0,933.0,432400.0,3417.0,82.0,5713.0,5713.0,2728.0,460313.974204,Atlanta-Sandy Springs-Alpharetta
120,2022-03-31,541000.0,470000.0,222.505964,214.056989,44.0,33.0,36.0,9.0,9.5,1.019758,0.590909,0.727273,ATL,30002,2022,14.0,1.0,3.0,1.0,69.0,70.0,62.0,4.0,14.0,6025.0,41.2,54743.0,6007.0,3149.0,933.0,432400.0,3417.0,82.0,5713.0,5713.0,2728.0,470108.846691,Atlanta-Sandy Springs-Alpharetta
121,2022-04-30,525000.0,470000.0,217.244325,213.028452,41.0,33.0,34.0,16.0,9.0,1.029642,0.707317,0.727273,ATL,30002,2022,14.0,1.0,3.0,1.0,69.0,69.0,61.0,4.0,14.0,6025.0,41.2,54743.0,6007.0,3149.0,933.0,432400.0,3417.0,82.0,5713.0,5713.0,2728.0,479486.188943,Atlanta-Sandy Springs-Alpharetta
122,2022-05-31,519000.0,525000.0,218.750000,226.103539,35.0,35.0,41.0,16.0,11.5,1.054090,0.742857,0.742857,ATL,30002,2022,14.0,1.0,3.0,1.0,69.0,69.0,61.0,4.0,14.0,6025.0,41.2,54743.0,6007.0,3149.0,933.0,432400.0,3417.0,82.0,5713.0,5713.0,2728.0,488436.530983,Atlanta-Sandy Springs-Alpharetta

In [18]:
train_df.to_csv("train_data.csv", index=False)
test_df.to_csv("test_data.csv", index=False)
eval_df.to_csv("new_data.csv", index=False)

In [19]:
ck = pd.read_csv("/content/new_data.csv")

ck.head()

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full
0,2022-01-31,575500.0,459900.0,211.746522,246.811160,45.0,39.0,35.0,21.0,17.0,1.005392,0.400000,0.538462,ATL,30002,2022,14.0,1.0,3.0,1.0,70.0,70.0,62.0,4.0,14.0,6025.0,41.2,54743.0,6007.0,3149.0,933.0,432400.0,3417.0,82.0,5713.0,5713.0,2728.0,452676.155824,Atlanta-Sandy Springs-Alpharetta
1,2022-02-28,574146.5,470000.0,215.718552,248.941469,48.0,33.0,36.0,18.0,16.0,1.010408,0.500000,0.696970,ATL,30002,2022,14.0,1.0,3.0,1.0,70.0,70.0,62.0,4.0,14.0,6025.0,41.2,54743.0,6007.0,3149.0,933.0,432400.0,3417.0,82.0,5713.0,5713.0,2728.0,460313.974204,Atlanta-Sandy Springs-Alpharetta
2,2022-03-31,541000.0,470000.0,222.505964,214.056989,44.0,33.0,36.0,9.0,9.5,1.019758,0.590909,0.727273,ATL,30002,2022,14.0,1.0,3.0,1.0,69.0,70.0,62.0,4.0,14.0,6025.0,41.2,54743.0,6007.0,3149.0,933.0,432400.0,3417.0,82.0,5713.0,5713.0,2728.0,470108.846691,Atlanta-Sandy Springs-Alpharetta
3,2022-04-30,525000.0,470000.0,217.244325,213.028452,41.0,33.0,34.0,16.0,9.0,1.029642,0.707317,0.727273,ATL,30002,2022,14.0,1.0,3.0,1.0,69.0,69.0,61.0,4.0,14.0,6025.0,41.2,54743.0,6007.0,3149.0,933.0,432400.0,3417.0,82.0,5713.0,5713.0,2728.0,479486.188943,Atlanta-Sandy Springs-Alpharetta
4,2022-05-31,519000.0,525000.0,218.750000,226.103539,35.0,35.0,41.0,16.0,11.5,1.054090,0.742857,0.742857,ATL,30002,2022,14.0,1.0,3.0,1.0,69.0,69.0,61.0,4.0,14.0,6025.0,41.2,54743.0,6007.0,3149.0,933.0,432400.0,3417.0,82.0,5713.0,5713.0,2728.0,488436.530983,Atlanta-Sandy Springs-Alpharetta

In [20]:
ck.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149424 entries, 0 to 149423
Data columns (total 39 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date                          149424 non-null  object
 1   median_sale_price             149424 non-null  float64
 2   median_list_price             149424 non-null  float64
 3   median_ppsf                   149424 non-null  float64
 4   median_list_ppsf              149424 non-null  float64
 5   homes_sold                    149424 non-null  float64
 6   pending_sales                 149424 non-null  float64
 7   new_listings                  149424 non-null  float64
 8   inventory                     149424 non-null  float64
 9   median_dom                    149424 non-null  float64
 10  avg_sale_to_list              149424 non-null  float64
 11  sold_above_list               149424 non-null  float64
 12  off_market_in_two_weeks       149424 non-null  float64
 13  city                          149424 non-null  object
 14  zipcode                       149424 non-null  int64
 15  year                          149424 non-null  int64
 16  bank                          149424 non-null  float64
 17  bus                           149424 non-null  float64
 18  hospital                      149424 non-null  float64
 19  mall                          149424 non-null  float64
 20  park                          149424 non-null  float64
 21  restaurant                    149424 non-null  float64
 22  school                        149424 non-null  float64
 23  station                       149424 non-null  float64
 24  supermarket                   149424 non-null  float64
 25  Total Population              149424 non-null  float64
 26  Median Age                    149424 non-null  float64
 27  Per Capita Income             149424 non-null  float64
 28  Total Families Below Poverty  149424 non-null  float64
 29  Total Housing Units           149424 non-null  float64
 30  Median Rent                   149424 non-null  float64
 31  Median Home Value             149424 non-null  float64
 32  Total Labor Force             149424 non-null  float64
 33  Unemployed Population         149424 non-null  float64
 34  Total School Age Population   149424 non-null  float64
 35  Total School Enrollment       149424 non-null  float64
 36  Median Commute Time           149424 non-null  float64
 37  price                         149424 non-null  float64
 38  city_full                     149424 non-null  object
dtypes: float64(34), int64(2), object(3)
memory usage: 44.5+ MB

In [21]:
from google.colab import files
files.download('/content/train_data.csv')

In [22]:
from google.colab import files
files.download('/content/test_data.csv')

In [23]:
from google.colab import files
files.download('/content/new_data.csv')