In [40]:
import pandas as pd
from category_encoders import TargetEncoder

In [41]:
train_df = pd.read_csv("../data/processed/processed_train_data.csv")
test_df = pd.read_csv("../data/processed/processed_test_data.csv")
new_df = pd.read_csv("../data/raw/new_data.csv")

pd.set_option('display.max_columns', None) # Show all columns
pd.set_option('display.max_rows', None) # Show all rows

In [42]:
train_df.head()

,date,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,year,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full,lat,lng
0,2012-03-31,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922
1,2012-04-30,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,0.946642,0.090909,0.034483,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922
2,2012-05-31,125500.0,217450.0,63.913043,119.919216,24.0,40.0,63.0,60.0,144.5,0.955624,0.208333,0.100000,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202681.309539,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922
3,2012-06-30,153000.0,189900.0,81.598080,105.617353,34.0,46.0,50.0,57.0,126.0,0.970608,0.176471,0.108696,ATL,30002,2012,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202998.603897,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922
4,2012-07-31,165500.0,154000.0,81.598080,83.921175,39.0,49.0,42.0,50.0,80.0,0.982105,0.256410,0.102041,ATL,30002,2012,12.0,2.0,3.0,1.0,60.0,45.0,57.0,4.0,6.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,203781.903446,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922

In [43]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576815 entries, 0 to 576814
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date                          576815 non-null  object
 1   median_sale_price             576815 non-null  float64
 2   median_list_price             576815 non-null  float64
 3   median_ppsf                   576815 non-null  float64
 4   median_list_ppsf              576815 non-null  float64
 5   homes_sold                    576815 non-null  float64
 6   pending_sales                 576815 non-null  float64
 7   new_listings                  576815 non-null  float64
 8   inventory                     576815 non-null  float64
 9   median_dom                    576815 non-null  float64
 10  avg_sale_to_list              576815 non-null  float64
 11  sold_above_list               576815 non-null  float64
 12  off_market_in_two_weeks       576815 non-null  float64
 13  city                          576815 non-null  object
 14  zipcode                       576815 non-null  int64
 15  year                          576815 non-null  int64
 16  bank                          576815 non-null  float64
 17  bus                           576815 non-null  float64
 18  hospital                      576815 non-null  float64
 19  mall                          576815 non-null  float64
 20  park                          576815 non-null  float64
 21  restaurant                    576815 non-null  float64
 22  school                        576815 non-null  float64
 23  station                       576815 non-null  float64
 24  supermarket                   576815 non-null  float64
 25  Total Population              576815 non-null  float64
 26  Median Age                    576815 non-null  float64
 27  Per Capita Income             576815 non-null  float64
 28  Total Families Below Poverty  576815 non-null  float64
 29  Total Housing Units           576815 non-null  float64
 30  Median Rent                   576815 non-null  float64
 31  Median Home Value             576815 non-null  float64
 32  Total Labor Force             576815 non-null  float64
 33  Unemployed Population         576815 non-null  float64
 34  Total School Age Population   576815 non-null  float64
 35  Total School Enrollment       576815 non-null  float64
 36  Median Commute Time           576815 non-null  float64
 37  price                         576815 non-null  float64
 38  city_full                     576815 non-null  object
 39  lat                           570488 non-null  float64
 40  lng                           570488 non-null  float64
dtypes: float64(36), int64(2), object(3)
memory usage: 180.4+ MB

In [44]:
print("Train Data: " + train_df.date.min() + " === " + train_df.date.max())
print("Test Data: " + test_df.date.min() + " === " + test_df.date.max())
print("New Data: " + new_df.date.min() + " === " + new_df.date.max())

Train Data: 2012-03-31 === 2019-12-31
Test Data: 2020-01-31 === 2021-11-30
New Data: 2022-01-31 === 2023-12-31

In [45]:
train_df['date'] = pd.to_datetime(train_df['date'])
test_df['date'] = pd.to_datetime(test_df['date'])
new_df['date'] = pd.to_datetime(new_df['date'])

In [46]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576815 entries, 0 to 576814
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date                          576815 non-null  datetime64[ns]
 1   median_sale_price             576815 non-null  float64
 2   median_list_price             576815 non-null  float64
 3   median_ppsf                   576815 non-null  float64
 4   median_list_ppsf              576815 non-null  float64
 5   homes_sold                    576815 non-null  float64
 6   pending_sales                 576815 non-null  float64
 7   new_listings                  576815 non-null  float64
 8   inventory                     576815 non-null  float64
 9   median_dom                    576815 non-null  float64
 10  avg_sale_to_list              576815 non-null  float64
 11  sold_above_list               576815 non-null  float64
 12  off_market_in_two_weeks       576815 non-null  float64
 13  city                          576815 non-null  object
 14  zipcode                       576815 non-null  int64
 15  year                          576815 non-null  int64
 16  bank                          576815 non-null  float64
 17  bus                           576815 non-null  float64
 18  hospital                      576815 non-null  float64
 19  mall                          576815 non-null  float64
 20  park                          576815 non-null  float64
 21  restaurant                    576815 non-null  float64
 22  school                        576815 non-null  float64
 23  station                       576815 non-null  float64
 24  supermarket                   576815 non-null  float64
 25  Total Population              576815 non-null  float64
 26  Median Age                    576815 non-null  float64
 27  Per Capita Income             576815 non-null  float64
 28  Total Families Below Poverty  576815 non-null  float64
 29  Total Housing Units           576815 non-null  float64
 30  Median Rent                   576815 non-null  float64
 31  Median Home Value             576815 non-null  float64
 32  Total Labor Force             576815 non-null  float64
 33  Unemployed Population         576815 non-null  float64
 34  Total School Age Population   576815 non-null  float64
 35  Total School Enrollment       576815 non-null  float64
 36  Median Commute Time           576815 non-null  float64
 37  price                         576815 non-null  float64
 38  city_full                     576815 non-null  object
 39  lat                           570488 non-null  float64
 40  lng                           570488 non-null  float64
dtypes: datetime64[ns](1), float64(36), int64(2), object(2)
memory usage: 180.4+ MB

In [47]:
def date_feature(df):
    df['year'] = df.date.dt.year
    df.insert(1, "year", df.pop("year"))
    df['quarter'] = df.date.dt.quarter
    df.insert(2, "quarter", df.pop("quarter"))
    df['month'] = df.date.dt.month
    df.insert(3, "month", df.pop("month"))

    return df

train_df = date_feature(train_df)
test_df = date_feature(test_df)
new_df = date_feature(new_df)

In [48]:
train_df.head()

,date,year,quarter,month,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full,lat,lng
0,2012-03-31,2012,1,3,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922
1,2012-04-30,2012,2,4,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,0.946642,0.090909,0.034483,ATL,30002,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922
2,2012-05-31,2012,2,5,125500.0,217450.0,63.913043,119.919216,24.0,40.0,63.0,60.0,144.5,0.955624,0.208333,0.100000,ATL,30002,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202681.309539,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922
3,2012-06-30,2012,2,6,153000.0,189900.0,81.598080,105.617353,34.0,46.0,50.0,57.0,126.0,0.970608,0.176471,0.108696,ATL,30002,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202998.603897,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922
4,2012-07-31,2012,3,7,165500.0,154000.0,81.598080,83.921175,39.0,49.0,42.0,50.0,80.0,0.982105,0.256410,0.102041,ATL,30002,12.0,2.0,3.0,1.0,60.0,45.0,57.0,4.0,6.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,203781.903446,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922

In [49]:
zip_freq = train_df["zipcode"].value_counts()

In [50]:
train_df["zipcode"].nunique()

6222

In [51]:
train_df["zipcode_freq"] = train_df["zipcode"].map(zip_freq)
test_df["zipcode_freq"] = test_df["zipcode"].map(zip_freq).fillna(0)
new_df["zipcode_freq"] = new_df["zipcode"].map(zip_freq).fillna(0)

In [52]:
train_df.head()

,date,year,quarter,month,median_sale_price,median_list_price,median_ppsf,median_list_ppsf,homes_sold,pending_sales,new_listings,inventory,median_dom,avg_sale_to_list,sold_above_list,off_market_in_two_weeks,city,zipcode,bank,bus,hospital,mall,park,restaurant,school,station,supermarket,Total Population,Median Age,Per Capita Income,Total Families Below Poverty,Total Housing Units,Median Rent,Median Home Value,Total Labor Force,Unemployed Population,Total School Age Population,Total School Enrollment,Median Commute Time,price,city_full,lat,lng,zipcode_freq
0,2012-03-31,2012,1,3,46550.0,217450.0,31.813674,110.183666,14.0,23.0,44.0,64.0,59.5,0.943662,0.142857,0.043478,ATL,30002,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,200773.999557,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922,94
1,2012-04-30,2012,2,4,61870.0,245000.0,40.723982,130.528256,22.0,29.0,56.0,69.0,89.5,0.946642,0.090909,0.034483,ATL,30002,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202421.064584,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922,94
2,2012-05-31,2012,2,5,125500.0,217450.0,63.913043,119.919216,24.0,40.0,63.0,60.0,144.5,0.955624,0.208333,0.100000,ATL,30002,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202681.309539,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922,94
3,2012-06-30,2012,2,6,153000.0,189900.0,81.598080,105.617353,34.0,46.0,50.0,57.0,126.0,0.970608,0.176471,0.108696,ATL,30002,12.0,2.0,4.0,1.0,60.0,45.0,57.0,4.0,7.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,202998.603897,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922,94
4,2012-07-31,2012,3,7,165500.0,154000.0,81.598080,83.921175,39.0,49.0,42.0,50.0,80.0,0.982105,0.256410,0.102041,ATL,30002,12.0,2.0,3.0,1.0,60.0,45.0,57.0,4.0,6.0,5811.0,36.3,33052.0,5811.0,2677.0,710.0,279500.0,3171.0,460.0,5408.0,5408.0,2492.0,203781.903446,"Atlanta-Sandy Springs-Roswell, GA",33.7338,-84.3922,94

In [53]:
te = TargetEncoder(cols=["city_full"])

train_df["city_encoded"] = te.fit_transform(train_df["city_full"], train_df["price"])
test_df["city_encoded"] = te.transform(test_df["city_full"])
new_df["city_encoded"] = te.transform(new_df["city_full"])

In [54]:
train_df[["city_full", "city_encoded"]].head()

                           city_full   city_encoded
0  Atlanta-Sandy Springs-Roswell, GA  192627.058387
1  Atlanta-Sandy Springs-Roswell, GA  192627.058387
2  Atlanta-Sandy Springs-Roswell, GA  192627.058387
3  Atlanta-Sandy Springs-Roswell, GA  192627.058387
4  Atlanta-Sandy Springs-Roswell, GA  192627.058387

In [55]:
drop_cols = ["date", "city_full", "city", "zipcode", "median_sale_price"]
train_df.drop(columns=drop_cols, inplace=True)
test_df.drop(columns=drop_cols, inplace=True)
new_df.drop(columns=drop_cols, inplace=True)

In [56]:
# Save the cleaned dataset
train_df.to_csv("../data/features/featured_train_data.csv", index=False)
test_df.to_csv("../data/features/featured_test_data.csv", index=False)
new_df.to_csv("../data/features/featured_new_data.csv", index=False)
print("Dataset saved successfully!")

Dataset saved successfully!